//
//  EmbeddedVocabularyData.swift
//  Scribe
//
//  Compiled internal vocabulary and phonetic dictionary.
//

import Foundation

public enum EmbeddedVocabularyData {
    public static let defaultCategories: [CommunityCategory] = [
        CommunityCategory(
            id: "ai_machine_learning",
            name: "AI & Machine Learning",
            languages: ["en", "ru"],
            terms: [
                "ChatGPT",
                "OpenAI",
                "Claude Code",
                "Claude",
                "Gemini",
                "DeepSeek",
                "Perplexity",
                "Midjourney",
                "Ollama",
                "WhisperKit",
                "PyTorch",
                "TensorFlow",
                "HuggingFace",
                "Antigravity",
                "Antigravity 2.0",
                "LangChain",
                "Llama",
                "LLM",
                "ИИ",
                "AI",
                "Mistral",
                "Qwen",
                "Anthropic",
                "Groq",
                "ElevenLabs",
            ]
        ),
        CommunityCategory(
            id: "developer_tools",
            name: "Developer Tools & Tech Stacks",
            languages: ["en", "ru"],
            terms: [
                "TypeScript",
                "JavaScript",
                "SwiftUI",
                "SwiftData",
                "TailwindCSS",
                "PostgreSQL",
                "Supabase",
                "Kubernetes",
                "Docker",
                "Next.js",
                "Rust",
                "GraphQL",
                "Vercel",
                "GitHub",
                "GitLab",
                "Firebase",
                "Firestore",
                "Xcode",
                "Cursor",
                "Windsurf",
                "Zed",
                "Ghostty",
                "vibe coding",
                "IDE",
                "Readme",
                "Пуш",
                "MCP",
            ]
        ),
        CommunityCategory(
            id: "scribe_ecosystem",
            name: "Scribe & Dictation Workflow",
            languages: ["en", "ru"],
            terms: [
                "Scribe",
                "транскрибатор",
                "транскрибация",
                "транскрибировать",
                "Aether",
                "Paperclip",
                "Floating Pill",
                "Liquid Glass",
                "Live Preview",
                "Preview",
                "Overlay",
                "Buzz",
            ]
        ),
        CommunityCategory(
            id: "slang_and_culture",
            name: "Modern Slang & Pop Culture",
            languages: ["en", "ru"],
            terms: [
                "топчик",
                "swag",
                "анскилл",
                "skill",
                "вайп",
                "вайб",
                "кринж",
                "хайп",
                "краш",
                "чилл",
                "флекс",
                "рофл",
                "пруф",
                "пофикси",
                "хоккей",
                "Миха",
                "Мам",
                "Пап",
                "Батя",
                "найс",
                "топ",
                "Google",
                "иконка",
                "bold",
                "waveform",
            ]
        ),
        CommunityCategory(
            id: "music_artists",
            name: "Music & Artists",
            languages: ["en", "ru"],
            terms: [
                "viperr",
                "Kai Angel",
                "9mice",
            ]
        ),
        CommunityCategory(
            id: "crypto_web3",
            name: "Crypto & Web3",
            languages: ["en", "ru"],
            terms: [
                "Bitcoin",
                "Ethereum",
                "Solana",
                "TON",
                "Bybit",
                "Binance",
                "MetaMask",
                "Tether",
                "TRC20",
                "ERC20",
                "Tonkeeper",
                "Uniswap",
            ]
        ),
        CommunityCategory(
            id: "social_media_services",
            name: "Apps, Notes & Platforms",
            languages: ["en", "ru", "de", "es", "fr"],
            terms: [
                "Telegram",
                "YouTube",
                "TikTok",
                "Instagram",
                "Discord",
                "Reddit",
                "Spotify",
                "Twitch",
                "LinkedIn",
                "Notion",
                "Obsidian",
                "Figma",
                "Apple Notes",
                "убери",
                "пофикси",
            ]
        ),
        CommunityCategory(
            id: "medicine_and_clinical",
            name: "Medicine & Clinical Healthcare",
            languages: ["en", "ru"],
            terms: [
                "МРТ",
                "КТ",
                "УЗИ",
                "ЭКГ",
                "ЭхоКГ",
                "Холтер",
                "ЭЭГ",
                "ФГДС",
                "Колоноскопия",
                "Бронхоскопия",
                "Рентгенография",
                "Флюорография",
                "Спирометрия",
                "Денситометрия",
                "Пункция",
                "Биопсия",
                "Лапароскопия",
                "Эндоскопия",
                "Ангиография",
                "Коронарография",
                "Сцинтиграфия",
                "ПЭТ-КТ",
                "ОАК",
                "ОАМ",
                "Биохимия крови",
                "Коагулограмма",
                "Липидограмма",
                "Гликированный гемоглобин",
                "СОЭ",
                "С-реактивный белок",
                "Ферритин",
                "Д-димер",
                "Тропонин",
                "Креатинин",
                "Мочевина",
                "АЛТ",
                "АСТ",
                "Билирубин",
                "Щелочная фосфатаза",
                "ГГТ",
                "Амилаза",
                "Липаза",
                "Мочевая кислота",
                "ТТГ",
                "Т3 свободный",
                "Т4 свободный",
                "Анти-ТПО",
                "Кортизол",
                "Пролактин",
                "Эстрадиол",
                "Прогестерон",
                "Тестостерон",
                "ДГЭА-сульфат",
                "ПСА",
                "Онкомаркеры",
                "СА-125",
                "РЭА",
                "АФП",
                "Кардиология",
                "Неврология",
                "Эндокринология",
                "Гастроэнтерология",
                "Пульмонология",
                "Онкология",
                "Гематология",
                "Нефрология",
                "Урология",
                "Гинекология",
                "Офтальмология",
                "Отоларингология",
                "Дерматология",
                "Ревматология",
                "Иммунология",
                "Аллергология",
                "Травматология",
                "Ортопедия",
                "Хирургия",
                "Нейрохирургия",
                "Анестезиология",
                "Реаниматология",
                "Психиатрия",
                "Психотерапия",
                "Инфекционист",
                "Фтизиатрия",
                "Токсикология",
                "Генетика",
                "Маммология",
                "Проктология",
                "Флебология",
                "Сомнология",
                "Интубация",
                "Трахеостомия",
                "Катетеризация",
                "Дефибрилляция",
                "Кардиоверсия",
                "Тромболизис",
                "Шунтирование",
                "Стентирование",
                "Резекция",
                "Экстирпация",
                "Ампутация",
                "Дренирование",
                "Тампонада",
                "Гемодиализ",
                "Плазмаферез",
                "Гемосорбция",
                "ИВЛ",
                "ЭКМО",
                "Вакцинация",
                "Иммунизация",
                "Седация",
                "Наркоз",
                "Реанимация",
                "Аускультация",
                "Пальпация",
                "Перкуссия",
                "Аспирин",
                "Ибупрофен",
                "Парацетамол",
                "Амоксициллин",
                "Азитромицин",
                "Цефтриаксон",
                "Дексаметазон",
                "Преднизолон",
                "Метотрексат",
                "Омепразол",
                "Пантопразол",
                "Аторвастатин",
                "Розувастатин",
                "Метформин",
                "Инсулин",
                "Лидокаин",
                "Новокаин",
                "Пропофол",
                "Фентанил",
                "Адреналин",
                "Норадреналин",
                "Атропин",
                "Нитроглицерин",
                "Амлодипин",
                "Лозартан",
                "Эналаприл",
                "Каптоприл",
                "Бисопролол",
                "Метопролол",
                "Фуросемид",
                "Спиронолактон",
                "Клексан",
                "Гепарин",
                "Варфарин",
                "Ксарелто",
                "Эликвис",
                "Апиксабан",
                "Мирамистин",
                "Хлоргексидин",
                "Бетадин",
                "Пантенол",
                "Спазмалгон",
                "Но-шпа",
                "Дротаверин",
                "Смекта",
                "Полисорб",
                "Энтеросгель",
                "Мезим",
                "Креон",
                "Панкреатин",
                "Метронидазол",
                "Флуконазол",
                "Ацикловир",
                "Валацикловир",
                "Цетиризин",
                "Лоратадин",
                "Супрастин",
                "Пульмикорт",
                "Беродуал",
                "Сальбутамол",
                "Амброксол",
                "Ацетилцистеин",
                "Кардиомагнил",
                "Мексидол",
                "Актовегин",
                "Церебролизин",
                "Пирацетам",
                "Фенибут",
                "Глицин",
                "Кортексин",
                "Афобазол",
                "Грандаксин",
                "Сертралин",
                "Эсциталопрам",
                "Ципралекс",
                "Золофт",
                "Кветиапин",
                "Оланзапин",
                "Диазепам",
                "MRI",
                "CT scan",
                "Ultrasound",
                "ECG",
                "Echocardiogram",
                "Holter monitor",
                "EEG",
                "Endoscopy",
                "Colonoscopy",
                "Biopsy",
                "Laparoscopy",
                "Angiography",
                "PET scan",
                "CBC",
                "CRP",
                "Ferritin",
                "D-dimer",
                "Troponin",
                "Creatinine",
                "BUN",
                "ALT",
                "AST",
                "Bilirubin",
                "TSH",
                "Cortisol",
                "Prolactin",
                "Estradiol",
                "Testosterone",
                "PSA",
                "Cardiology",
                "Neurology",
                "Endocrinology",
                "Gastroenterology",
                "Pulmonology",
                "Oncology",
                "Hematology",
                "Nephrology",
                "Urology",
                "Gynecology",
                "Ophthalmology",
                "ENT",
                "Dermatology",
                "Rheumatology",
                "Immunology",
                "Anesthesiology",
                "Psychiatry",
                "Intubation",
                "Defibrillation",
                "Thrombolysis",
                "Stenting",
                "Hemodialysis",
                "ECMO",
            ]
        ),
        CommunityCategory(
            id: "nutrition_and_dietetics",
            name: "Nutrition, Supplements & Biohacking",
            languages: ["en", "ru"],
            terms: [
                "Витамин А",
                "Ретинол",
                "Витамин B1",
                "Тиамин",
                "Витамин B2",
                "Рибофлавин",
                "Витамин B3",
                "Ниацин",
                "Никотинамид",
                "Витамин B5",
                "Пантотеновая кислота",
                "Витамин B6",
                "Пиридоксин",
                "P-5-P",
                "Витамин B7",
                "Биотин",
                "Витамин B9",
                "Фолиевая кислота",
                "Метилфолат",
                "Витамин B12",
                "Метилкобаламин",
                "Витамин C",
                "Аскорбиновая кислота",
                "Аскорбат натрия",
                "Витамин D3",
                "Холекальциферол",
                "Витамин E",
                "Токоферол",
                "Витамин K1",
                "Витамин K2",
                "Менахинон",
                "МК-7",
                "Магний",
                "Цитрат магния",
                "Глицинат магния",
                "Малат магния",
                "Треонат магния",
                "Таурат магния",
                "Цинк",
                "Пиколинат цинка",
                "Хелат цинка",
                "Селен",
                "Селенометионин",
                "Железо",
                "Бисглицинат железа",
                "Хелат железа",
                "Кальций",
                "Калий",
                "Йод",
                "Келп",
                "Медь",
                "Марганец",
                "Хром",
                "Пиколинат хрома",
                "Молибден",
                "Бор",
                "Кремний",
                "MSM",
                "Метилсульфонилметан",
                "Омега-3",
                "ЭПК",
                "EPA",
                "ДГК",
                "DHA",
                "Омега-6",
                "Омега-9",
                "Фосфолипиды",
                "Лецитин",
                "Холин",
                "Фосфатидилсерин",
                "Инозитол",
                "Мио-инозитол",
                "D-хироинозитол",
                "МСТ масло",
                "Альфа-липоевая кислота",
                "Коэнзим Q10",
                "Убихинон",
                "Убихинол",
                "PQQ",
                "NAD+",
                "NMN",
                "Ресвератрол",
                "Кверцетин",
                "Куркумин",
                "Берберин",
                "Глутатион",
                "Липосомальный глутатион",
                "NAC",
                "N-ацетилцистеин",
                "Астаксантин",
                "Ликопин",
                "Лютеин",
                "Зеаксантин",
                "Спирулина",
                "Хлорелла",
                "Родиола розовая",
                "Ашваганда",
                "KSM-66",
                "Бакопа Монье",
                "Кордицепс",
                "Рейши",
                "Ежовик гребенчатый",
                "Lion's Mane",
                "Трибулус",
                "Мака перуанская",
                "Гинкго билоба",
                "5-HTP",
                "Мелатонин",
                "ГАМК",
                "GABA",
                "L-теанин",
                "L-тирозин",
                "L-триптофан",
                "L-карнитин",
                "Ацетил-L-карнитин",
                "Таурин",
                "Креатин моногидрат",
                "Бета-аланин",
                "BCAA",
                "Лейцин",
                "Изолейцин",
                "Валин",
                "L-глутамин",
                "L-аргинин",
                "L-цитруллин",
                "Коллаген",
                "Пептиды коллагена",
                "Гиалуроновая кислота",
                "Глюкозамин",
                "Хондроитин",
                "Пробиотики",
                "Пребиотики",
                "Синбиотики",
                "Постбиотики",
                "Лактобактерии",
                "Бифидобактерии",
                "Бутират",
                "Псиллиум",
                "Инулин",
                "Клетчатка",
                "Энзимы",
                "Пепсин",
                "Бетаин гидрохлорид",
                "Панкреатин",
                "Бромелайн",
                "Папаин",
                "БЖУ",
                "Белки",
                "Жиры",
                "Углеводы",
                "Гликемический индекс",
                "Инсулиновый индекс",
                "Калорийность",
                "Базальный метаболизм",
                "BMR",
                "Дефицит калорий",
                "Профицит калорий",
                "Кетоз",
                "Кетогенная диета",
                "Интервальное голодание",
                "Автофагия",
                "Гликолиз",
                "Глюконеогенез",
                "Липолиз",
                "Окисление жиров",
                "Цикл Кребса",
                "Метилирование",
                "Детоксикация",
                "Митохондриальная дисфункция",
                "Оксидативный стресс",
                "Антиоксиданты",
                "Инсулинорезистентность",
                "Лептинорезистентность",
                "Микробиом",
                "Дисбиоз",
                "Синдром дырявого кишечника",
                "Vitamin A",
                "Vitamin B-Complex",
                "Vitamin C",
                "Vitamin D3",
                "Vitamin K2",
                "Magnesium Glycinate",
                "Magnesium L-Threonate",
                "Zinc Picolinate",
                "Selenium",
                "Iron Bisglycinate",
                "Omega-3",
                "EPA",
                "DHA",
                "Phospholipids",
                "Choline",
                "Phosphatidylserine",
                "Inositol",
                "MCT Oil",
                "Coenzyme Q10",
                "Ubiquinol",
                "NAD+",
                "NMN",
                "Resveratrol",
                "Quercetin",
                "Curcumin",
                "Berberine",
                "Glutathione",
                "NAC",
                "Ashwagandha",
                "Lion's Mane",
                "Cordyceps",
                "L-Theanine",
                "L-Tyrosine",
                "Creatine Monohydrate",
                "Collagen Peptides",
                "Hyaluronic Acid",
                "Probiotics",
                "Prebiotics",
                "Microbiome",
                "Ketosis",
                "Autophagy",
                "Glycolysis",
                "Insulin Resistance",
            ]
        ),
        CommunityCategory(
            id: "diseases_and_pathology",
            name: "Diseases, Syndromes & Pathology",
            languages: ["en", "ru"],
            terms: [
                "Артериальная гипертензия",
                "ИБС",
                "Стенокардия",
                "Инфаркт миокарда",
                "Атеросклероз",
                "Аритмия",
                "Мерцательная аритмия",
                "Фибрилляция предсердий",
                "Тахикардия",
                "Брадикардия",
                "Экстрасистолия",
                "Сердечная недостаточность",
                "ХСН",
                "Эндокардит",
                "Миокардит",
                "Перикардит",
                "Кардиомиопатия",
                "Тромбоз",
                "Тромбофлебит",
                "ТЭЛА",
                "Варикозное расширение вен",
                "Инсульт",
                "Ишемический инсульт",
                "Геморрагический инсульт",
                "ТИА",
                "Аневризма",
                "Сахарный диабет 1 типа",
                "Сахарный диабет 2 типа",
                "Гестационный диабет",
                "Гипогликемия",
                "Гипергликемия",
                "Метаболический синдром",
                "Гипотиреоз",
                "Гипертиреоз",
                "Тиреотоксикоз",
                "Аутоиммунный тиреоидит",
                "АИТ",
                "Болезнь Хашимото",
                "Болезнь Грейвса",
                "Базедова болезнь",
                "Диффузный токсический зоб",
                "Узловой зоб",
                "Подострый тиреоидит",
                "Надпочечниковая недостаточность",
                "Болезнь Аддисона",
                "Синдром Иценко-Кушинга",
                "Феохромоцитома",
                "Гиперпролактинемия",
                "СПКЯ",
                "Эндометриоз",
                "Ожирение",
                "Гастрит",
                "Острый гастрит",
                "Хронический гастрит",
                "Атрофический гастрит",
                "Язвенная болезнь",
                "ГЭРБ",
                "Эзофагит",
                "Дуоденит",
                "Панкреатит",
                "Холецистит",
                "ЖКБ",
                "ДЖВП",
                "Гепатит",
                "НАСГ",
                "НАЖБП",
                "Цирроз печени",
                "СРК",
                "СИБР",
                "СИГР",
                "Болезнь Крона",
                "НЯК",
                "Целиакия",
                "Дисбактериоз",
                "Колит",
                "Проктит",
                "Геморрой",
                "Аппендицит",
                "Перитонит",
                "Пневмония",
                "Бронхит",
                "Бронхиальная астма",
                "ХОБЛ",
                "Эмфизема легких",
                "Плеврит",
                "Пневмоторакс",
                "ОРВИ",
                "Грипп",
                "COVID-19",
                "Коронавирус",
                "Синусит",
                "Гайморит",
                "Фронтит",
                "Ринит",
                "Тонзиллит",
                "Фарингит",
                "Ларингит",
                "Отит",
                "Трахеит",
                "Аденоиды",
                "Туберкулез",
                "Остеохондроз",
                "Межпозвоночная грыжа",
                "Протрузия диска",
                "Радикулит",
                "Ишиас",
                "Люмбаго",
                "Спондилез",
                "Артрит",
                "Ревматоидный артрит",
                "Подагра",
                "Остеоартроз",
                "Коксартроз",
                "Гонартроз",
                "Остеопороз",
                "Сколиоз",
                "Кифоз",
                "Бурсит",
                "Синовит",
                "Тендинит",
                "Фасциит",
                "Пяточная шпора",
                "Миалгия",
                "Фибромиалгия",
                "Синдром запястного канала",
                "Мигрень",
                "Головная боль напряжения",
                "Кластерная головная боль",
                "ВСД",
                "Эпилепсия",
                "Рассеянный склероз",
                "Болезнь Альцгеймера",
                "Болезнь Паркинсона",
                "Деменция",
                "БАС",
                "Невралгия тройничного нерва",
                "Неврит лицевого нерва",
                "Полинейропатия",
                "Энцефалопатия",
                "Менингит",
                "Энцефалит",
                "Сотрясение головного мозга",
                "Бессонница",
                "Инсомния",
                "СОАС",
                "Депрессия",
                "Клиническая депрессия",
                "Тревожное расстройство",
                "ГТР",
                "Панические атаки",
                "Фобии",
                "ОКР",
                "ПТСР",
                "БАР",
                "СДВГ",
                "Шизофрения",
                "Невроз",
                "Эмоциональное выгорание",
                "Астения",
                "Дерматит",
                "Атопический дерматит",
                "Себорейный дерматит",
                "Контактный дерматит",
                "Псориаз",
                "Экзема",
                "Акне",
                "Розацеа",
                "Крапивница",
                "Отек Квинке",
                "Алопеция",
                "Грибок",
                "Микоз",
                "Онихомикоз",
                "Герпес",
                "Опоясывающий лишай",
                "ВПЧ",
                "Пиелонефрит",
                "Гломерулонефрит",
                "Цистит",
                "МКБ",
                "Нефролитиаз",
                "ХПН",
                "Простатит",
                "Аденома простаты",
                "ДГПЖ",
                "Варикоцеле",
                "Анемия",
                "Железодефицитная анемия",
                "Лейкоз",
                "Лимфома",
                "Лимфаденит",
                "Тромбоцитопения",
                "Гемофилия",
                "Hypertension",
                "Coronary Artery Disease",
                "Myocardial Infarction",
                "Atherosclerosis",
                "Arrhythmia",
                "Atrial Fibrillation",
                "Heart Failure",
                "Thrombosis",
                "Pulmonary Embolism",
                "Stroke",
                "Type 1 Diabetes",
                "Type 2 Diabetes",
                "Hypothyroidism",
                "Hashimoto's Thyroiditis",
                "Graves' Disease",
                "Cushing's Syndrome",
                "PCOS",
                "Gastritis",
                "GERD",
                "Pancreatitis",
                "Cholecystitis",
                "Cirrhosis",
                "IBS",
                "SIBO",
                "Crohn's Disease",
                "Ulcerative Colitis",
                "Celiac Disease",
                "Pneumonia",
                "Asthma",
                "COPD",
                "COVID-19",
                "Rheumatoid Arthritis",
                "Gout",
                "Osteoarthritis",
                "Osteoporosis",
                "Fibromyalgia",
                "Migraine",
                "Multiple Sclerosis",
                "Alzheimer's Disease",
                "Parkinson's Disease",
                "Epilepsy",
                "Depression",
                "Generalized Anxiety Disorder",
                "Panic Disorder",
                "OCD",
                "PTSD",
                "ADHD",
                "Psoriasis",
                "Eczema",
                "Atopic Dermatitis",
                "Acne",
                "Rosacea",
                "Chronic Kidney Disease",
                "Anemia",
            ]
        ),
        CommunityCategory(
            id: "cities_islands_and_locations",
            name: "Cities, Islands & Locations",
            languages: ["en", "ru", "ar"],
            terms: [
                "Абу-Даби", "Abu Dhabi",
                "Саадият", "остров Саадият", "Saadiyat Island", "Saadiyat",
                "Яс", "остров Яс", "Yas Island", "Yas",
                "Рим", "Аль-Рим", "остров Аль-Рим", "Al Reem Island", "Reem Island", "Al Reem",
                "Аль-Марьях", "остров Аль-Марьях", "Al Maryah Island", "Al Maryah",
                "Джубайл", "остров Джубайл", "Jubail Island", "Jubail",
                "Худайрият", "остров Худайрият", "Hudayriyat Island", "Hudayriyat",
                "Нурай", "остров Нурай", "Nurai Island", "Nurai",
                "Лулу", "остров Лулу", "Lulu Island",
                "Сир-Бани-Яс", "Sir Bani Yas", "Дельма", "Delma Island",
                "Аль-Мая", "Al Maya Island", "Гантут", "Ghantoot",
                "Корниш", "Корниш Роуд", "Corniche Road", "Corniche",
                "Шейх Заед", "Шейх Зайд", "Sheikh Zayed Road", "Sheikh Zayed",
                "Шейх Рашид Бин Саид", "Sheikh Rashid Bin Saeed Street",
                "улица Хамдан", "Hamdan Street", "Hamdan",
                "улица Халифа", "Khalifa Street", "Khalifa",
                "улица Электра", "Electra Street", "Electra",
                "Аль-Салам", "Al Salam Street", "Al Salam",
                "Аль-Фалах", "Al Falah Street",
                "Аэропорт Роуд", "Airport Road",
                "Мурур Роуд", "Muroor Road", "Muroor",
                "Наджа", "Najda Street", "Najda",
                "Порт Заед", "Zayed Port", "Мина Заед", "Mina Zayed",
                "Аль-Батин", "Al Bateen",
                "Аль-Халидия", "Al Khalidiyah", "Khalidiyah",
                "Аль-Захия", "Al Zahiyah", "Tourist Club Area",
                "Аль-Карама", "Al Karamah",
                "Аль-Мушриф", "Al Mushrif",
                "Масдар Сити", "Masdar City", "Masdar",
                "Аль-Раха", "Al Raha Beach", "Al Raha",
                "Аль-Риф", "Al Reef",
                "Халифа Сити", "Khalifa City",
                "Мохамед Бин Заед Сити", "Mohamed Bin Zayed City", "MBZ City",
                "Яс Марина", "Yas Marina", "Яс Молл", "Yas Mall",
                "Феррари Ворлд", "Ferrari World",
                "Лувр Абу-Даби", "Louvre Abu Dhabi",
                "Гуггенхайм", "Guggenheim Abu Dhabi",
                "Мечеть Шейха Заеда", "Sheikh Zayed Grand Mosque",
                "Каср Аль-Ватан", "Qasr Al Watan",
                "Эмирейтс Палас", "Emirates Palace",
                "Дубай", "Dubai",
                "Палм-Джумейра", "Palm Jumeirah",
                "Блювотерс", "Bluewaters Island", "Bluewaters",
                "Палм-Джебель-Али", "Palm Jebel Ali",
                "Дубай Айлендс", "Dubai Islands", "Дейра Айлендс", "Deira Islands",
                "Мировые острова", "The World Islands",
                "Дубай Марина", "Dubai Marina", "Marina",
                "Даунтаун Дубай", "Downtown Dubai", "Downtown",
                "Бурдж-Халифа", "Burj Khalifa",
                "Джумейра Бич", "JBR", "Jumeirah Beach Residence",
                "Бизнес Бэй", "Business Bay",
                "DIFC", "Dubai International Financial Centre",
                "Сити Вок", "City Walk",
                "Ла Мер", "La Mer",
                "Крик Харбор", "Dubai Creek Harbour",
                "Мейдан", "Meydan",
                "Аль-Барша", "Al Barsha",
                "Джумейра Лейкс Тауэрс", "JLT", "Jumeirah Lake Towers",
                "Джебель-Али", "Jebel Ali",
                "Дейра", "Deira", "Бур-Дубай", "Bur Dubai",
                "Хатта", "Hatta", "Шарджа", "Sharjah", "Аджман", "Ajman",
                "Рас-эль-Хайма", "Ras Al Khaimah", "Фуджейра", "Fujairah", "Умм-эль-Кайвайн", "Umm Al Quwain",
                "Манхэттен", "Manhattan", "Бруклин", "Brooklyn", "Квинс", "Queens",
                "Стейтен-Айленд", "Staten Island", "Бродвей", "Broadway", "Пятая авеню", "Fifth Avenue",
                "Таймс-сквер", "Times Square", "Уолл-стрит", "Wall Street",
                "Лондон", "London", "Оксфорд-стрит", "Oxford Street", "Бейкер-стрит", "Baker Street",
                "Пикадилли", "Piccadilly", "Сохо", "Soho", "Кенсингтон", "Kensington", "Канари-Уорф", "Canary Wharf",
                "Париж", "Paris", "Елисейские поля", "Champs-Élysées", "Монмартр", "Montmartre",
                "Москва", "Moscow", "Тверская", "Арбат", "Новый Арбат", "Садовое кольцо", "Кутузовский проспект",
                "Патриаршие пруды", "Патрики", "Хамовники", "Москва-Сити",
                "Санкт-Петербург", "Невский проспект", "Васильевский остров", "Крестовский остров",
                "Бали", "Bali", "Чангу", "Canggu", "Семиньяк", "Seminyak", "Убуд", "Ubud", "Улувату", "Uluwatu", "Нуса-Пенида", "Nusa Penida",
                "Пхукет", "Phuket", "Самуи", "Koh Samui", "Бангкок", "Bangkok",
                "Сингапур", "Singapore", "Сентоза", "Sentosa Island", "Гонконг", "Hong Kong",
                "Токио", "Tokyo", "Сибуя", "Shibuya", "Синдзюку", "Shinjuku", "Гиндза", "Ginza",
                "Стамбул", "Istanbul", "Истикляль", "Istiklal", "Кадыкёй", "Kadikoy", "Бешикташ", "Besiktas"
            ]
        ),
    ]

    public static let defaultPhoneticMap: [String: String] = [
        "чат гпт": "ChatGPT",
        "чатгпт": "ChatGPT",
        "chat gpt": "ChatGPT",
        "джипити": "ChatGPT",
        "опенаи": "OpenAI",
        "опен аи": "OpenAI",
        "опенэй": "OpenAI",
        "open ai": "OpenAI",
        "клод код": "Claude Code",
        "клауд код": "Claude Code",
        "клод": "Claude",
        "клауд": "Claude",
        "джеминай": "Gemini",
        "гемнай": "Gemini",
        "джемини": "Gemini",
        "дипсик": "DeepSeek",
        "дип сик": "DeepSeek",
        "deep seek": "DeepSeek",
        "перплексити": "Perplexity",
        "перплексити аи": "Perplexity",
        "perplexity ai": "Perplexity",
        "миджорни": "Midjourney",
        "мидджорни": "Midjourney",
        "mid journey": "Midjourney",
        "оллама": "Ollama",
        "olama": "Ollama",
        "виперкит": "WhisperKit",
        "уисперкит": "WhisperKit",
        "whisper kit": "WhisperKit",
        "пайторч": "PyTorch",
        "питорч": "PyTorch",
        "питч": "PyTorch",
        "py torch": "PyTorch",
        "тензорфлоу": "TensorFlow",
        "тензорфло": "TensorFlow",
        "tensor flow": "TensorFlow",
        "хаггинг фейс": "HuggingFace",
        "хаггингфейс": "HuggingFace",
        "hugging face": "HuggingFace",
        "антигравити": "Antigravity",
        "анти-гравити": "Antigravity",
        "анти гравити": "Antigravity",
        "anti gravity": "Antigravity",
        "антиградик": "Antigravity",
        "антигравити 2 0": "Antigravity 2.0",
        "антигравити два ноль": "Antigravity 2.0",
        "лэнгчейн": "LangChain",
        "лангчейн": "LangChain",
        "lang chain": "LangChain",
        "лама": "Llama",
        "ллама": "Llama",
        "элэлэм": "LLM",
        "ллм": "LLM",
        "л л м": "LLM",
        "и и": "ИИ",
        "иишка": "ИИ",
        "эй ай": "AI",
        "аи": "AI",
        "мистраль": "Mistral",
        "квен": "Qwen",
        "антропик": "Anthropic",
        "грок": "Groq",
        "элевенлабс": "ElevenLabs",
        "элевен лабс": "ElevenLabs",
        "тайпскрипт": "TypeScript",
        "тайп скрипт": "TypeScript",
        "type script": "TypeScript",
        "джаваскрипт": "JavaScript",
        "яваскрипт": "JavaScript",
        "java script": "JavaScript",
        "свифт юай": "SwiftUI",
        "свифтюай": "SwiftUI",
        "swift ui": "SwiftUI",
        "свифт дата": "SwiftData",
        "свифтдата": "SwiftData",
        "swift data": "SwiftData",
        "тайлвинд": "TailwindCSS",
        "тейлвинд": "TailwindCSS",
        "тайлвиндксс": "TailwindCSS",
        "тейлвинд цсс": "TailwindCSS",
        "tailwind": "TailwindCSS",
        "постгрес": "PostgreSQL",
        "постгре": "PostgreSQL",
        "постгрескл": "PostgreSQL",
        "постгрес скл": "PostgreSQL",
        "postgres": "PostgreSQL",
        "супабейс": "Supabase",
        "супабейз": "Supabase",
        "supa base": "Supabase",
        "кубернетес": "Kubernetes",
        "кубер": "Kubernetes",
        "к8с": "Kubernetes",
        "k8s": "Kubernetes",
        "докер": "Docker",
        "некст": "Next.js",
        "некстджс": "Next.js",
        "некст джс": "Next.js",
        "nextjs": "Next.js",
        "раст": "Rust",
        "раста": "Rust",
        "графкл": "GraphQL",
        "графкьюэл": "GraphQL",
        "graph ql": "GraphQL",
        "версель": "Vercel",
        "версел": "Vercel",
        "гитхаб": "GitHub",
        "гит хаб": "GitHub",
        "git hub": "GitHub",
        "гитлаб": "GitLab",
        "гит лаб": "GitLab",
        "файрбейз": "Firebase",
        "файрбейс": "Firebase",
        "файербейз": "Firebase",
        "файрстор": "Firestore",
        "файерстор": "Firestore",
        "икскод": "Xcode",
        "экс код": "Xcode",
        "курсор": "Cursor",
        "кёрсор": "Cursor",
        "виндсерф": "Windsurf",
        "виндсёрф": "Windsurf",
        "зед": "Zed",
        "зэд": "Zed",
        "гости": "Ghostty",
        "гостти": "Ghostty",
        "вайб кодинг": "vibe coding",
        "вайбкодинг": "vibe coding",
        "вайб кодингом": "vibe coding",
        "vibe code": "vibe coding",
        "иде": "IDE",
        "айди": "IDE",
        "ай ди и": "IDE",
        "ридми": "Readme",
        "рид ми": "Readme",
        "readme md": "Readme",
        "push": "Пуш",
        "пушить": "Пуш",
        "пушнуть": "Пуш",
        "эм си пи": "MCP",
        "эмсипи": "MCP",
        "скрайб": "Scribe",
        "скриб": "Scribe",
        "аджанскребатор": "транскрибатор",
        "транскребатор": "транскрибатор",
        "тридцать кибаксов": "транскрибатор",
        "транскриптор": "транскрибатор",
        "транскребация": "транскрибация",
        "скребация": "транскрибация",
        "трескребация": "транскрибация",
        "раскребация": "транскрибация",
        "трескребаться": "транскрибировать",
        "транскрибить": "транскрибировать",
        "эфир": "Ethereum",
        "эйтер": "Aether",
        "аэтер": "Aether",
        "пейпер клип": "Paperclip",
        "пейперклип": "Paperclip",
        "скрепка": "Paperclip",
        "флотинг пил": "Floating Pill",
        "уфлотинг пил": "Floating Pill",
        "ликвит глаз": "Liquid Glass",
        "ликвид глаз": "Liquid Glass",
        "лайф привью": "Live Preview",
        "лайфпривью": "Live Preview",
        "лайв превью": "Live Preview",
        "превью": "Preview",
        "привью": "Preview",
        "оверлей": "Overlay",
        "оверлэй": "Overlay",
        "базз": "Buzz",
        "баз": "Buzz",
        "top chick": "топчик",
        "top chic": "топчик",
        "топ чик": "топчик",
        "topchik": "топчик",
        "свэг": "swag",
        "свэгг": "swag",
        "swagg": "swag",
        "ан скилл": "анскилл",
        "ан скил": "анскилл",
        "анскил": "анскилл",
        "unskill": "анскилл",
        "скилл": "skill",
        "скил": "skill",
        "wipe": "вайп",
        "vibe": "вайб",
        "вайбик": "вайб",
        "cringe": "кринж",
        "кринжа": "кринж",
        "кринжуха": "кринж",
        "hype": "хайп",
        "crush": "краш",
        "chill": "чилл",
        "чилить": "чилл",
        "flex": "флекс",
        "флексить": "флекс",
        "rofl": "рофл",
        "рофлить": "рофл",
        "proof": "пруф",
        "пруфы": "пруф",
        "пофиксить": "пофикси",
        "зафикси": "пофикси",
        "hockey": "хоккей",
        "хакей": "хоккей",
        "мих": "Миха",
        "михаил": "Миха",
        "мама": "Мам",
        "мамка": "Мам",
        "папа": "Пап",
        "папка": "Пап",
        "батяня": "Батя",
        "бать": "Батя",
        "nice": "найс",
        "top": "топ",
        "вайпер": "viperr",
        "вайперр": "viperr",
        "viper": "viperr",
        "кай энджел": "Kai Angel",
        "кай ангел": "Kai Angel",
        "кайэнджел": "Kai Angel",
        "девять майс": "9mice",
        "9 майс": "9mice",
        "nine mice": "9mice",
        "биткоин": "Bitcoin",
        "биток": "Bitcoin",
        "btc": "Bitcoin",
        "эфириум": "Ethereum",
        "eth": "Ethereum",
        "солана": "Solana",
        "сол": "Solana",
        "sol": "Solana",
        "тон": "TON",
        "тонкоин": "TON",
        "toncoin": "TON",
        "байбит": "Bybit",
        "бай бит": "Bybit",
        "бинанс": "Binance",
        "бинансе": "Binance",
        "метамаск": "MetaMask",
        "мета маск": "MetaMask",
        "тезер": "Tether",
        "тетер": "Tether",
        "usdt": "Tether",
        "трц20": "TRC20",
        "трц 20": "TRC20",
        "ерц20": "ERC20",
        "ерц 20": "ERC20",
        "тонkeeper": "Tonkeeper",
        "тон кипер": "Tonkeeper",
        "юнисвоп": "Uniswap",
        "юнисвап": "Uniswap",
        "телеграм": "Telegram",
        "телега": "Telegram",
        "ютуб": "YouTube",
        "ютьюб": "YouTube",
        "тикток": "TikTok",
        "тик ток": "TikTok",
        "инстаграм": "Instagram",
        "инста": "Instagram",
        "дискорд": "Discord",
        "реддит": "Reddit",
        "спотифай": "Spotify",
        "твич": "Twitch",
        "линкедин": "LinkedIn",
        "ноушен": "Notion",
        "ношен": "Notion",
        "обсидиан": "Obsidian",
        "фигма": "Figma",
        "эппл ноутс": "Apple Notes",
        "эппл заметки": "Apple Notes",
        "отобили": "убери",
        "ото били": "убери",
        "ото бери": "убери",
        "пафикси": "пофикси",
        "по фикси": "пофикси",
        // Cities, Islands & Street Location Phonetic Mappings
        "абу даби": "Абу-Даби",
        "абудаби": "Абу-Даби",
        "саадият": "Саадият",
        "саадият айленд": "Saadiyat Island",
        "остров саадият": "остров Саадият",
        "саддият": "Саадият",
        "садият": "Саадият",
        "яс айленд": "Yas Island",
        "остров яс": "остров Яс",
        "аль рим": "Аль-Рим",
        "альрим": "Аль-Рим",
        "рим айленд": "Reem Island",
        "аль рим айленд": "Al Reem Island",
        "остров аль рим": "остров Аль-Рим",
        "аль марьях": "Аль-Марьях",
        "альмарьях": "Аль-Марьях",
        "марьях айленд": "Al Maryah Island",
        "джубайл": "Джубайл",
        "джубайл айленд": "Jubail Island",
        "остров джубайл": "остров Джубайл",
        "худайрият": "Худайрият",
        "остров худайрият": "остров Худайрият",
        "нурай": "Нурай",
        "нурай айленд": "Nurai Island",
        "остров нурай": "остров Нурай",
        "сир бани яс": "Сир-Бани-Яс",
        "корниш": "Корниш",
        "корниш роуд": "Corniche Road",
        "шейх заед": "Шейх Заед",
        "шейх зайд": "Шейх Зайд",
        "шейх заед роуд": "Sheikh Zayed Road",
        "шейх рашид": "Шейх Рашид",
        "улица хамдан": "улица Хамдан",
        "улица халифа": "улица Халифа",
        "улица электра": "улица Электра",
        "аль салам": "Аль-Салам",
        "масдар": "Масдар Сити",
        "масдар сити": "Masdar City",
        "аль раха": "Аль-Раха",
        "аль риф": "Аль-Риф",
        "халифа сити": "Халифа Сити",
        "мбз": "MBZ City",
        "палм джумейра": "Palm Jumeirah",
        "пальма джумейра": "Palm Jumeirah",
        "блювотерс": "Bluewaters Island",
        "блю вотерс": "Bluewaters Island",
        "дубай марина": "Dubai Marina",
        "дубаймарина": "Dubai Marina",
        "даунтаун": "Downtown",
        "бизнес бэй": "Business Bay",
        "бизнес бей": "Business Bay",
        "сити вок": "City Walk",
        "ла мер": "La Mer",
        "оксфорд стрит": "Oxford Street",
        "бейкер стрит": "Baker Street",
        "елисейские поля": "Champs-Élysées",
        "чангу": "Canggu",
        "семиньяк": "Seminyak",
        "убуд": "Ubud",
        "улувату": "Uluwatu",
        "сентоза": "Sentosa Island",
    ]
}
