import Foundation

/// Central localization manager for Scribe interface text.
enum Localization {
    
    /// Returns the localized string for a given key and UI language code.
    static func string(_ key: String, lang: String) -> String {
        let code = effectiveLanguageCode(lang)
        if let langDict = translations[code], let text = langDict[key] {
            return text
        }
        // Fallback to English
        if let enDict = translations["en"], let text = enDict[key] {
            return text
        }
        return key
    }
    
    private static func effectiveLanguageCode(_ lang: String) -> String {
        if lang != "auto" { return lang }
        // Detect system language
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? "en"
        if preferred.hasPrefix("ru") { return "ru" }
        if preferred.hasPrefix("es") { return "es" }
        if preferred.hasPrefix("de") { return "de" }
        if preferred.hasPrefix("fr") { return "fr" }
        if preferred.hasPrefix("it") { return "it" }
        if preferred.hasPrefix("zh") { return "zh" }
        if preferred.hasPrefix("ja") { return "ja" }
        if preferred.hasPrefix("pt") { return "pt" }
        if preferred.hasPrefix("tr") { return "tr" }
        if preferred.hasPrefix("uk") { return "uk" }
        if preferred.hasPrefix("pl") { return "pl" }
        if preferred.hasPrefix("nl") { return "nl" }
        if preferred.hasPrefix("ko") { return "ko" }
        if preferred.hasPrefix("ar") { return "ar" }
        if preferred.hasPrefix("hi") { return "hi" }
        if preferred.hasPrefix("sv") { return "sv" }
        if preferred.hasPrefix("kk") { return "kk" }
        if preferred.hasPrefix("id") { return "id" }
        if preferred.hasPrefix("vi") { return "vi" }
        if preferred.hasPrefix("th") { return "th" }
        if preferred.hasPrefix("cs") { return "cs" }
        if preferred.hasPrefix("el") { return "el" }
        if preferred.hasPrefix("he") { return "he" }
        if preferred.hasPrefix("ro") { return "ro" }
        if preferred.hasPrefix("hu") { return "hu" }
        if preferred.hasPrefix("da") { return "da" }
        if preferred.hasPrefix("fi") { return "fi" }
        if preferred.hasPrefix("no") { return "no" }
        if preferred.hasPrefix("sk") { return "sk" }
        if preferred.hasPrefix("bg") { return "bg" }
        if preferred.hasPrefix("hr") { return "hr" }
        if preferred.hasPrefix("sr") { return "sr" }
        if preferred.hasPrefix("uz") { return "uz" }
        if preferred.hasPrefix("az") { return "az" }
        return "en"
    }
    
    // MARK: - Translations Dictionary
    
    private static let translations: [String: [String: String]] = [
        "en": [
            "Start Dictation": "Start Dictation",
            "Stop Dictation": "Stop Dictation",
            "Transcribing…": "Transcribing…",
            "Transcribing": "Transcribing",
            "Hotkey: ⌥S": "Hotkey: ⌥S",
            "Settings…": "Settings…",
            "Dictation Language": "Dictation Language",
            "Interface Language": "Interface Language",
            "Quit Scribe": "Quit Scribe",
            "Scribe Settings": "Scribe Settings",
            "General": "General",
            "Recording": "Recording",
            "Global Hotkey": "Global Hotkey",
            "Paste Mode": "Paste Mode",
            "Replace": "Replace",
            "Append": "Append",
            "Replaces clipboard content with transcribed text.": "Replaces clipboard content with transcribed text.",
            "Appends transcribed text to current clipboard content.": "Appends transcribed text to current clipboard content.",
            "Live Preview": "Live Preview",
            "Shows intermediate text while recording": "Shows intermediate text while recording",
            "Display Mode": "Display Mode",
            "Floating Pill": "Floating Pill",
            "Inside Card": "Inside Card",
            "Preview Background": "Preview Background",
            "Scribe transcribes your speech live…": "Scribe transcribes your speech live…",
            "Appearance": "Appearance",
            "Theme": "Theme",
            "Overlay Style": "Overlay Style",
            "Overlay Size": "Overlay Size",
            "Overlay Position": "Overlay Position",
            "Active Window": "Active Window",
            "Screen Bottom": "Screen Bottom",
            "Waveform": "Waveform",
            "Classic": "Classic",
            "Panel Appearance": "Panel Appearance",
            "Dark": "Dark",
            "Light": "Light",
            "Glass": "Glass",
            "Recognition": "Recognition",
            "Model Quality": "Model Quality",
            "Permissions": "Permissions",
            "Accessibility Permission": "Accessibility Permission",
            "Granted": "Granted",
            "Not Granted": "Not Granted",
            "Microphone Permission": "Microphone Permission",
            "System": "System",
            "View Transcription History": "View Transcription History",
            "Version": "Version",
            "History": "History",
            "Clear All": "Clear All",
            "Search transcriptions…": "Search transcriptions…",
            "No transcriptions yet": "No transcriptions yet",
            "No results found": "No results found",
            "Record something with ⌥S to get started": "Record something with ⌥S to get started",
            "Copy Text": "Copy Text",
            "Copied": "Copied!",
            "Delete": "Delete",
            "Recording…": "Recording…",
            "Loading model…": "Loading model…",
            "Done ✓": "Done ✓",
            "Small (Recommended)": "Small (Recommended)",
            "Great balance of high accuracy and speed (~460MB)": "Great balance of high accuracy and speed (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Highest quality for complex speech & terms (~950MB)",
            "Base (Fastest)": "Base (Fastest)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Lightweight and ultra fast, ideal for simple phrases (~140MB)",
            "Setting a specific language improves accuracy on short phrases.": "Setting a specific language improves accuracy on short phrases.",
            "Lumina": "Lumina",
            "Midnight": "Midnight",
            "Emerald": "Emerald",
            "Auto Translate to Selected Language": "Auto Translate to Selected Language",
            "Minimal": "Minimal",
            "Magic": "Magic",
            "Pulse": "Pulse",
            "Statistics": "Statistics",
            "Today": "Today",
            "This Week": "This Week",
            "All Time": "All Time",
            "Words Spoken": "Words Spoken",
            "Characters": "Characters",
            "Time Dictated": "Time Dictated",
            "Sessions": "Sessions",
        
            "Live Floating Preview": "Live Floating Preview",
            "Launch at Login": "Launch at Login",
            "Sound Feedback": "Sound Feedback",
            "Microphone": "Microphone",
            "Accessibility": "Accessibility",
            "Grant Access": "Grant Access",
            "Support Scribe": "Support Scribe",
        
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!",
            "Buy Me a Coffee on Ko-fi": "Buy Me a Coffee on Ko-fi",
            "or Crypto": "or Crypto",
            "Aether": "Aether",
            "Aether Hybrid": "Aether Hybrid",
            "Aether Hybrid (Recommended)": "Aether Hybrid (Recommended)",
            "Aether Turbo": "Aether Turbo",
            "Aether Instant": "Aether Instant",
            "3-Stage Pipeline Active": "3-Stage Pipeline Active",
            "Multilingual Mode": "Multilingual Mode",
            "Multilingual Mode (2-3 Languages)": "Multilingual Mode (2-3 Languages)",
            "Aether combines Audio VAD, dynamic app context conditioning, and lexical fuzzy matching for zero-hallucination, studio-grade speech transcription.": "Aether combines Audio VAD, dynamic app context conditioning, and lexical fuzzy matching for zero-hallucination, studio-grade speech transcription.",
            "Aether Instant uses Apple's built-in native speech engine with zero model downloads (~0 MB) and instant real-time transcription.": "Aether Instant uses Apple's built-in native speech engine with zero model downloads (~0 MB) and instant real-time transcription.",
            "Aether Turbo uses lightweight quantized Whisper models for fast, low-latency offline dictation.": "Aether Turbo uses lightweight quantized Whisper models for fast, low-latency offline dictation.",
            "LEVEL UP!": "LEVEL UP!",
            "Promoted to": "Promoted to",
            "RANK TIER": "RANK TIER",
            "STREAK HONOUR": "STREAK HONOUR",
            "Active Day": "Active Day",
            "Active Days": "Active Days",
            "VOLUME AWARD": "VOLUME AWARD",
            "PROGRESS": "PROGRESS",
            "Mastery": "Mastery",
            "words to Level": "words to Level",
            "Words": "Words",
            "words": "words",
            "Words remaining": "Words remaining",
            "CERTIFICATE OF MASTERY": "CERTIFICATE OF MASTERY",
            "Conferred for outstanding dedication and voice dictation mastery": "Conferred for outstanding dedication and voice dictation mastery"
        ],
        "ru": [
            "Sign In": "Войти",
            "Sign In to Scribe": "Вход в Scribe",
            "Sign in to sync your statistics, history, and subscriptions in future across all your devices.": "Войдите, чтобы синхронизировать статистику, историю и подписки в будущем между всеми устройствами.",
            "Continue with Google": "Продолжить через Google",
            "Continue with Apple": "Продолжить через Apple",
            "Continue with Email": "Продолжить через Email",
            "Continue with GitHub": "Продолжить через GitHub",
            "Start Dictation": "Начать диктовку",
            "Stop Dictation": "Завершить диктовку",
            "Transcribing…": "Транскрибация…",
            "Transcribing": "Транскрибация",
            "Hotkey: ⌥S": "Горячая клавиша: ⌥S",
            "Settings…": "Настройки…",
            "Dictation Language": "Язык диктовки",
            "Interface Language": "Язык интерфейса",
            "Quit Scribe": "Завершить Scribe",
            "Scribe Settings": "Настройки Scribe",
            "General": "Основные",
            "Recording": "Запись",
            "Global Hotkey": "Горячая клавиша",
            "Paste Mode": "Режим вставки",
            "Replace": "Замена",
            "Append": "Добавление",
            "Replaces clipboard content with transcribed text.": "Заменяет содержимое буфера обмена на распознанный текст.",
            "Appends transcribed text to current clipboard content.": "Добавляет распознанный текст к текущему содержимому буфера.",
            "Live Preview": "Живой просмотр",
            "Shows intermediate text while recording": "Показывает текст прямо во время записи",
            "Clean Filler Words": "Очистка мусорных слов",
            "Removes hesitations (\"uh\", \"um\", \"эээ\", \"ну\") and duplicate words": "Удаляет слова-паразиты («эээ», «ну», «типа», «uh», «um») и повторы речи",
            "Import IT & AI Terms Preset": "Импортировать IT & AI пресет",
            "Display Mode": "Режим отображения",
            "Floating Pill": "Отдельный баббл",
            "Inside Card": "Внутри оверлея",
            "Preview Background": "Фон превью",
            "Scribe transcribes your speech live…": "Scribe распознает вашу речь на лету…",
            "Appearance": "Внешний вид",
            "Theme": "Тема оформления",
            "Overlay Style": "Стиль оверлея",
            "Overlay Size": "Размер оверлея",
            "Overlay Position": "Положение оверлея",
            "Active Window": "Под активным окном",
            "Screen Bottom": "Внизу экрана",
            "Overlay Size Preview": "Предпросмотр размера",
            "Waveform": "Волна",
            "Classic": "Классический",
            "Panel Appearance": "Тема панели",
            "Dark": "Темная",
            "Light": "Светлая",
            "Glass": "Стекло",
            "Recognition": "Распознавание",
            "Model Quality": "Качество модели",
            "Permissions": "Разрешения",
            "Accessibility Permission": "Доступ к Универсальному доступу",
            "Granted": "Разрешено",
            "Not Granted": "Не разрешено",
            "Microphone Permission": "Доступ к микрофону",
            "System": "Система",
            "View Transcription History": "Открыть историю транскрипций",
            "Version": "Версия",
            "History": "История",
            "Clear All": "Очистить всё",
            "Search transcriptions…": "Поиск по историям…",
            "No transcriptions yet": "Записей пока нет",
            "No results found": "Ничего не найдено",
            "Record something with ⌥S to get started": "Натисніть ⌥S щоб начать запись",
            "Copy Text": "Скопировать текст",
            "Copied": "Скопировано!",
            "Delete": "Удалить",
            "Recording…": "Запись…",
            "Loading model…": "Загрузка модели…",
            "Done ✓": "Готово ✓",
            "Small (Recommended)": "Маленькая (Рекомендуется)",
            "Great balance of high accuracy and speed (~460MB)": "Отличный баланс скорости и точности (~460 МБ)",
            "Large V3 Turbo": "Большая V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Высшее качество для сложной речи и терминов (~950 МБ)",
            "Base (Fastest)": "Базовая (Самая быстрая)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Легкая и сверхбыстрая, идеальна для простых фраз (~140 МБ)",
            "Setting a specific language improves accuracy on short phrases.": "Выбор языка вручную улучшает точность на коротких фразах.",
            "Lumina": "Lumina",
            "Midnight": "Midnight",
            "Emerald": "Emerald",
            "Auto Translate to Selected Language": "Автоматический перевод на выбранный язык",
            "Minimal": "Компактный",
            "Magic": "Магия",
            "Pulse": "Пульс",
            "Statistics": "Статистика",
            "Today": "Сегодня",
            "This Week": "На этой неделе",
            "All Time": "За всё время",
            "Words Spoken": "Сказано слов",
            "Characters": "Символов",
            "Time Dictated": "Время диктовки",
            "Sessions": "Сессий",
        
            "Live Floating Preview": "Плавающее превью",
            "Launch at Login": "Запускать при входе",
            "Sound Feedback": "Звуковой отклик",
            "Show Recording Timer": "Показывать таймер записи",
            "Show Target Application": "Показывать целевое приложение",
            "Microphone": "Микрофон",
            "Accessibility": "Универсальный доступ",
            "Grant Access": "Предоставить доступ",
            "Support Scribe": "Поддержать Scribe",
            "Options": "Опции",
            "OPTIONS": "ОПЦИИ",
            "Output Options": "Параметры вывода",
            "Solid": "Сплошной",
            "Transparent": "Прозрачный",
            "Certificate Color": "Цвет сертификата",
            "CERTIFICATE COLOR": "ЦВЕТ СЕРТИФИКАТА",
            "Gold Theme": "Золотая тема",
            "Level Theme": "Тема уровня",
            "Original phrase": "Исходная фраза",
            "Replacement": "Замена",
            "Replacements": "Автозамена",
            "Integrations Only": "Только интеграции",
            "Replaces clipboard content and pastes into active window.": "Заменяет содержимое буфера обмена и вставляет в активное окно.",
            "Exports directly to selected notes app without pasting into active window.": "Экспортирует сразу в заметки без вставки в активное окно.",
            "Target Apps": "Приложения для заметок",
            "Select 1 or more apps for direct export": "Выберите 1 или более приложений для экспорта",
            "Direct Note Shortcut": "Хоткей записи в заметки",
            "Send text straight to notes app": "Отправлять текст сразу в заметки",
            "Direct Note Target App": "Приложение для прямых заметок",
            "Search transcriptions...": "Поиск по записям…",
            "Back": "Назад",
            "About Scribe": "О Scribe",
            "Welcome": "Добро пожаловать",
            "Voice Test": "Проверка голоса",
            "Start Test": "Начать проверку",
            "Stop Test": "Остановить проверку",
            "Profile": "Профиль",
            "Get Started": "Начать работу",
            "Your Name or Nickname": "Ваше имя или никнейм",
            "Choose how you want Scribe to look when recording.": "Выберите, как Scribe будет выглядеть во время записи.",
            "Customize Look": "Настройка внешнего вида",
            "Push-to-Talk (Hold)": "Push-to-Talk (удержание)",
            "Hold key to record, release to stop": "Удерживайте клавишу для записи, отпустите для остановки",
            "Direct Note Recording": "Запись прямо в заметки",
            "Separate hotkey for direct notes export": "Отдельный хоткей для моментальной записи в заметки",
            "Language": "Язык",
            "History & Statistics": "История и статистика",
        
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe — это независимый проект, поддерживаемый исключительно за счет пожертвований пользователей. Если он оказался вам полезен, вы можете поддержать его разработку. Пожертвования абсолютно добровольны. Спасибо!",
            "Buy Me a Coffee on Ko-fi": "Купить мне кофе на Ko-fi",
            "or Crypto": "или Крипта",

            "Scribe App Edition": "Версия приложения Scribe",
            "Pro Edition: Enables ultra-fast Cloud AI, LLM text refinement (summaries, executive tone, action items) & Cloud Sync.": "Pro версия: Включает сверхбыстрый Cloud AI, ИИ-обработку текста (саммари, деловой стиль, списки задач) и облачную синхронизацию.",
            "Base Edition: Free offline dictation, local Whisper models, text replacements, and notes integrations.": "Базовая версия: Бесплатная офлайн-диктовка, локальные модели Whisper, автозамена текста и интеграция со заметками.",

            "and for subscriptions in future": "и для подписок в будущем",
            "What should we call you?": "Как к вам обращаться?",
            "Enter your name or nickname to personalize Scribe": "Введите ваше имя или никнейм для персонализации Scribe",
            "Your name or nickname...": "Ваше имя или ник...",
            "Continue": "Продолжить",
            "Account Settings": "Настройки аккаунта",
            "Nickname / Display Name": "Никнейм / Имя",
            "Enter nickname": "Введите никнейм",
            "Save": "Сохранить",
            "Name updated successfully!": "Имя успешно обновлено!",
            "Reset / Change Password": "Сбросить / Сменить пароль",
            "Password reset email sent to": "Письмо сброса пароля отправлено на",
            "Sign Out": "Выйти из аккаунта",
            "Delete Account": "Удалить аккаунт",
            "Are you sure you want to delete your account? This action cannot be undone and your synced data will be removed.": "Вы уверены, что хотите удалить аккаунт? Это действие нельзя отменить, а ваши синхронизированные данные будут удалены.",
            "GitHub Sign In": "Вход через GitHub",
            "GitHub Username or Email": "Имя пользователя или Email GitHub",
            "octocat or user@github.com": "octocat или user@github.com",
            "Continue with GitHub Profile": "Продолжить с профилем GitHub",

            "Recognition Engine": "Движок распознавания",
            "Aether": "Aether",
            "Aether Hybrid": "Aether Hybrid",
            "Aether Hybrid (Recommended)": "Aether Hybrid (Рекомендуется)",
            "Aether Turbo": "Aether Turbo",
            "Aether Instant": "Aether Instant",
            "3-Stage Pipeline Active": "3-этапный пайплайн активен",
            "Multilingual Mode": "Многоязычный режим",
            "Multilingual Mode (2-3 Languages)": "Многоязычный режим (2-3 языка)",
            "Single Language Mode": "Одноязычный режим",
            "Aether combines Audio VAD, dynamic app context conditioning, and lexical fuzzy matching for zero-hallucination, studio-grade speech transcription.": "Aether объединяет VAD-фильтрацию тишины, контекст активного приложения и нечеткий словарный матчер для точной диктовки без галлюцинаций.",
            "Aether Instant uses Apple's built-in native speech engine with zero model downloads (~0 MB) and instant real-time transcription.": "Aether Instant использует встроенный системный движок Apple Speech без скачивания моделей (~0 МБ) и нагрузок на процессор.",
            "Aether Turbo uses lightweight quantized Whisper models for fast, low-latency offline dictation.": "Aether Turbo использует легковесные квантованные модели Whisper для быстрой оффлайн-диктовки с низкой задержкой.",
            "LEVEL UP!": "НОВЫЙ УРОВЕНЬ!",
            "Promoted to": "Повышение до",
            "Dictation Language(s)": "Язык(и) диктовки",
            "Select up to 3 languages": "Выберите до 3 языков",
            "Selected (%d)": "Выбрано (%d)",
            "Auto-Detect": "Автоопределение",
            "Vocabulary": "Словарь",
            "Vocabulary Presets": "Пресеты словаря",
            "Create Preset": "Создать пресет",
            "Import Preset": "Импортировать пресет",
            "Create Vocabulary Preset": "Создание пресета словаря",
            "Import Vocabulary Preset": "Импорт пресета словаря",
            "Preset Name": "Название пресета",
            "Description (Optional)": "Описание (необязательно)",
            "Words & Acronyms": "Слова и аббревиатуры",
            "Min 2 characters": "От 2 символов",
            "Generated Share Code": "Код для шеринга",
            "Save Preset": "Сохранить пресет",
            "words": "слов",
            "Active Custom Vocabulary": "Активный словарь",
            "Active Blocked Words": "Активные стоп-слова",
            "Dictionary Mode:": "Режим словаря:",
            "Blocked Words Presets": "Пресеты запрещённых слов",
            "Create Blocked Words Preset": "Создание пресета стоп-слов",
            "Import Blocked Preset": "Импорт пресета стоп-слов",
            "Create custom word packs and share them instantly.": "Создавайте собственные наборы слов и делитесь ими.",
            "Create custom blocked word packs and share them instantly.": "Создавайте наборы запрещённых слов и делитесь ими.",
            "Share Active Words": "Поделиться активными словами",
            "Share Active Blocked Words": "Поделиться стоп-словами",
            "Share Words": "Поделиться словами",
            "Select Words to Share": "Выберите слова для отправки",
            "Select All": "Выбрать все",
            "Deselect All": "Снять выбор",
            "selected": "выбрано",
            "Share Selected Words": "Поделиться выбранными",
            "Filter words...": "Поиск по словам...",
            "No words match your search.": "Нет слов, подходящих под поиск.",
            "Delete Preset": "Удаление пресета",
            "Delete Preset & Keep Words": "Удалить пресет, но оставить слова",
            "Delete Preset & Remove Words": "Удалить пресет и убрать слова из активных",
            "Do you want to keep the words from this preset in your active dictionary, or remove them as well?": "Хотите оставить слова из этого пресета в активном словаре или также удалить их?",
            "Also add to active blocked words": "Также сразу добавить в активные стоп-слова",
            "Scribe automatically filters common Whisper hallucination artifacts (subtitles, credits). Add your custom blocked words and sensitive terms below.": "В Scribe уже вшита автоматическая фильтрация системных галлюцинаций Whisper (субтитры, спасибо за просмотр и др.). Сюда вы можете добавить свои нежелательные слова и стоп-фразы.",
            "Blocked Words & Phrases": "Запрещённые слова и фразы",
            "e.g. Profanity Filter, Competitor Names, Sensitive Terms...": "напр. Ненормативная лексика, Конфиденциальные термины...",
            "Add blocked word or comma-separated list...": "Введите запрещённое слово или список через запятую...",
            "No custom presets yet. Create one or import a share code to get started.": "Пока нет кастомных пресетов. Создайте свой или введите код для импорта.",
            "All words below will be prioritized and automatically capitalized by Whisper.": "Все указанные слова будут автоматически капитализированы и распознаны Whisper.",
            "Applied!": "Применено!",
            "Copied!": "Скопировано!",
            "Copy Code": "Скопировать код",
            "Share Code (scr_...)": "Код пресета (scr_...)",
            "Paste scr_ code here...": "Вставьте код scr_...",
            "Also add words directly into active vocabulary": "Также сразу добавить слова в активный словарь",
            "Improve Scribe Vocabulary": "Улучшение словаря Scribe",
            "Can Scribe anonymously use your added custom words and presets to train better recognition models and expand the built-in vocabulary for everyone?": "Может ли Scribe анонимно использовать добавленные вами слова и пресеты для обучения моделей распознавания и расширения встроенной библиотеки для всех пользователей?",
            "100% Anonymous & Secure": "100% анонимно и безопасно",
            "No voice audio, full transcripts, notes, or personal identifiers are ever collected. Only isolated vocabulary terms and acronyms.": "Аудиозаписи, полные тексты транскрипций, заметки и личные данные никогда не собираются. Только отдельные словарные слова и аббревиатуры.",
            "No, Thanks": "Не сейчас",
            "Allow & Improve": "Разрешить",
            "Community Improvement": "Улучшение словаря сообществом",
            "Contribute to Scribe Vocabulary": "Участвовать в улучшении словаря",
            "Anonymously share added vocabulary terms to expand the built-in library for everyone.": "Анонимно делиться новыми словами для расширения встроенной библиотеки для всех.",
            "Add custom words, names, or acronyms to help Scribe recognize them correctly.": "Добавляйте слова, имена или аббревиатуры для точного распознавания.",
            "Add custom words, names, or acronyms to help Scribe recognize them correctly. Separate words with commas.": "Добавляйте собственные слова, имена или аббревиатуры, чтобы Scribe правильно их распознавал. Разделяйте слова запятыми.",
            "Integrations": "Интеграции",
            "Supported Note Apps": "Приложения для заметок",
            "Send transcripts directly to Obsidian": "Отправлять транскрипции прямо в Obsidian",
            "Select Vault Folder": "Выбрать папку хранилища",
            "No vault selected": "Папка не выбрана",
            "Target Note:": "Целевая заметка:",
            "e.g. Scribe Transcriptions": "напр. Записи Scribe",
            "Apple Notes": "Заметки Apple",
            "Send transcripts directly to Apple Notes": "Отправлять транскрипции прямо в Заметки Apple",
            "Save Destination:": "Куда сохранять:",
            "Single Note (Append)": "В одну заметку (дополнять)",
            "New Note per Speech": "Новая заметка для каждой речи",
            "Use 'Scribe Notes'": "Заметка 'Scribe Notes'",
            "Set destination to dedicated Scribe note": "Использовать отдельную заметку Scribe",
            "Each dictation will automatically create a new note in Apple Notes with title and timestamp.": "Каждая речь будет сохраняться в отдельную новую заметку с заголовком и датой.",
            "Notion": "Notion",
            "Send transcripts directly to Notion": "Отправлять транскрипции прямо в Notion",
            "API Token:": "Токен API:",
            "Secret Token": "Секретный токен",
            "Page ID:": "ID страницы:",
            "Target Page ID": "ID целевой страницы",
            "Day Streak": "Дней подряд",
            "Total Sessions": "Всего сессий",
            "Tap!": "Нажми!",
            "Enable Direct Note Feature": "Включить запись прямо в заметки",
            "Quick shortcut to dictate straight to your notes app": "Отдельный хоткей для моментальной записи в заметки",
            "Add Date & Time Header": "Добавлять дату и время в заметку",
            "Prefix exported notes with timestamp (e.g. 11.08.2026 17:21)": "Добавлять метку времени (например, 11.08.2026 17:21) перед заметкой",
            "CERTIFICATE OF EXCELLENCE": "СЕРТИФИКАТ ДОСТИЖЕНИЙ",
            "OFFICIAL RECORD": "ОФИЦИАЛЬНЫЙ СЕРТИФИКАТ",
            "CERTIFICATE OF MASTERY": "СЕРТИФИКАТ МАСТЕРСТВА",
            "Conferred for outstanding dedication and voice dictation mastery": "За выдающуюся продуктивность и голосовое мастерство",
            "has achieved the rank of": "достиг(ла) звания",
            "User": "Пользователь",
            "Push-to-Talk (Hold to record)": "Push-to-Talk (удерживание)",
            "Hold the hotkey to record, release to stop": "Удерживайте клавишу для записи, отпустите для остановки",
            "Recognition Mode": "Режим распознавания",
            "Dictation Languages": "Языки диктовки",
            "Select up to 3 languages for auto-switching": "Выберите до 3 языков для мгновенного переключения",
            "Single Language": "Единственный язык",
            "Insertion & Export Mode": "Режим вставки и заметок",
            "Active Window + Notes": "В активное окно + Заметки",
            "Notes Only (No Window Paste)": "Только в Заметки (без вставки в окно)",
            "Active Window Only": "Только в активное окно",
            "Blocked Words": "Запрещённые слова",
            "Words that will never appear in transcription": "Слова и фразы, которые никогда не появятся в распознанном тексте.",
            "Action for blocked words:": "Действие при обнаружении:",
            "Remove from text": "Удалять из текста",
            "Mask with ***": "Заменять на ***",
            "Add Whisper Hallucinations Preset": "Пресет галлюцинаций Whisper",
            "Enter blocked word or phrase...": "Введите запрещённое слово или фразу...",
            "No blocked words added yet.": "Запрещённые слова пока не добавлены.",
            "Custom Vocabulary": "Словарь и акронимы",
            "Action After Transcription": "Действие после транскрибации",

            "Drip": "Капля",
            "Trickle": "Струйка",
            "Puddle": "Лужица",
            "Drinking Fountain": "Родник",
            "Leaky Faucet": "Живой Ключ",
            "Garden Hose": "Водный Поток",
            "Sprinkler": "Дождеватель",
            "Kitchen Tap": "Водосброс",
            "Rain Shower": "Проливной дождь",
            "Spring": "Горный Исток",
            "Brook": "Лесной ручей",
            "Creek": "Быстрый Поток",
            "Rivulet": "Речка",
            "Stream": "Поток",
            "Runoff": "Сток",
            "Storm Drain": "Ливневка",
            "Fountain": "Фонтан",
            "Mill Race": "Водосброс",
            "Cascade": "Каскад",
            "Rapids": "Пороги",
            "Tributary": "Приток",
            "River": "Река",
            "Delta": "Дельта",
            "Estuary": "Эстуарий",
            "Reservoir": "Водохранилище",
            "Lake": "Озеро",
            "Bay": "Залив",
            "Sound": "Пролив",
            "Gulf": "Морской залив",
            "Inland Sea": "Внутреннее море",
            "Sea": "Море",
            "Open Ocean": "Открытый океан",
            "Deep Current": "Глубинное течение",
            "Geyser": "Гейзер",
            "Waterfall": "Водопад",
            "Niagara Falls": "Ниагарский водопад",
            "Broken Dam": "Прорванная плотина",
            "Storm Surge": "Штормовой нагон",
            "Whirlpool": "Водоворот",
            "Maelstrom": "Мальстрим",
            "Rogue Wave": "Волна-убийца",
            "Monsoon": "Муссон",
            "Flash Flood": "Внезапный паводок",
            "Deluge": "Потоп",
            "Hurricane": "Ураган",
            "Typhoon": "Тайфун",
            "Tidal Wave": "Приливная волна",
            "Tsunami": "Цунами",
            "Category 5": "Категория 5",
            "Force of Nature": "Стихия",
            "Manage Password on Google.com": "Управление паролем на Google.com",
            "Opened official Google password reset page in browser.": "В браузере открыта страница восстановления пароля Google.",
            "Cities & Locations": "Города и локации",
            "Location & Country Presets": "Пресеты стран и локаций",
            "Location Presets": "Пресеты локаций",
            "Specify your city, frequent neighborhoods or street names (comma-separated). Scribe will bias the transcription model to accurately recognize local addresses, street prefixes, and locations.": "Укажите ваш город, частые районы или улицы (через запятую). Scribe оптимизирует модель для точного распознавания местных адресов, улиц и топонимов.",
            "e.g. London, Oxford St, Soho or Dubai, Marina, Abu Dhabi...": "напр. Лондон, Оксфорд-стрит, Сохо или Дубай, Марина, Абу-Даби...",
            "Quick presets:": "Быстрые города:",
            "Create Location Preset": "Создать пресет локаций",
            "Import Location Preset": "Импортировать пресет",
            "Software Updates": "Обновления приложения",
            "Check for Updates": "Проверить обновления",
            "Checking for updates...": "Проверка обновлений...",
            "Update Available": "Доступно обновление",
            "Update available": "Доступно обновление",
            "Updating...": "Обновление...",
            "Install & Restart": "Установить и перезапустить",
            "Update Now": "Обновить сейчас",
            "Up to date": "Установлена актуальная версия",
            "Auto-checks GitHub every 30s": "Автопроверка GitHub каждые 30 сек",
            "Current Version": "Текущая версия",
            "Latest Version": "Последняя версия",
            "Downloading update...": "Загрузка обновления...",
            "Cities, Countries & Locations": "Города, страны и локации",
            "Create Location & Country Preset": "Создать пресет стран и локаций",
            "Import Location & Country Preset": "Импортировать пресет стран и локаций",
            "Open GitHub OAuth Settings": "Открыть настройки GitHub OAuth",
            "Confirm sign in in browser": "Подтвердите вход в браузере",
            "Waiting for browser sign in…": "Ожидание входа через браузер…",
            "Code copied to clipboard. Paste it in your browser.": "Код скопирован в буфер. Вставьте его в браузере.",
            "Complete sign in in the opened browser window.": "Завершите авторизацию в открывшемся окне браузера.",
            "RANK TIER": "РАНГ",
            "STREAK HONOUR": "СЕРИЯ ДНЕЙ",
            "Active Day": "день подряд",
            "Active Days": "дн. подряд",
            "VOLUME AWARD": "ОБЪЁМ СЛОВ",
            "PROGRESS": "ПРОГРЕСС",
            "Mastery": "мастерства",
            "words to Level": "слов до ур.",
            "Words": "слов",
            "Words remaining": "Осталось слов",
            "Verify Transfer": "Подтвердить перевод",
            "Enter sender wallet address or TxID": "Адрес кошелька отправителя или TxID",
            "Checking blockchain...": "Проверка в блокчейне...",
            "Donation verified!": "Донат подтвержден!",
            "Thank you for supporting Scribe!": "Спасибо за поддержку Scribe!",
            "Transaction not found yet. If sent recently, please wait 1-2 minutes for network confirmation and try again.": "Транзакция пока не найдена. Если перевод сделан недавно, подождите 1–2 минуты подтверждения сети и попробуйте снова.",
            "HONOURED SCRIBE SUPPORTER": "ПОЧЁТНЫЙ МЕЦЕНАТ SCRIBE",
            "You are a verified Scribe Supporter!": "Вы являетесь верифицированным меценатом Scribe!"
        ],
        "es": [
            "Start Dictation": "Iniciar dictado",
            "Stop Dictation": "Detener dictado",
            "Transcribing…": "Transcribiendo…",
            "Hotkey: ⌥S": "Atajo: ⌥S",
            "Settings…": "Ajustes…",
            "Dictation Language": "Idioma de dictado",
            "Interface Language": "Idioma de interfaz",
            "Quit Scribe": "Salir de Scribe",
            "Scribe Settings": "Ajustes de Scribe",
            "Recording": "Grabación",
            "Global Hotkey": "Atajo global",
            "Paste Mode": "Modo de pegado",
            "Replace": "Reemplazar",
            "Append": "Añadir",
            "Replaces clipboard content with transcribed text.": "Reemplaza el portapapeles con el texto transcrito.",
            "Appends transcribed text to current clipboard content.": "Añade el texto transcrito al portapapeles actual.",
            "Live Preview": "Vista previa en vivo",
            "Shows intermediate text while recording": "Muestra el texto mientras grabas",
            "Preview Background": "Fondo de vista previa",
            "Appearance": "Apariencia",
            "Theme": "Tema",
            "Overlay Style": "Estilo de superposición",
            "Waveform": "Forma de onda",
            "Classic": "Clásico",
            "Panel Appearance": "Apariencia del panel",
            "Dark": "Oscuro",
            "Light": "Claro",
            "Glass": "Cristal",
            "Recognition": "Reconocimiento",
            "Model Quality": "Calidad del modelo",
            "Permissions": "Permisos",
            "Accessibility Permission": "Permiso de accesibilidad",
            "Granted": "Concedido",
            "Not Granted": "No concedido",
            "Microphone Permission": "Permiso de micrófono",
            "System": "Sistema",
            "View Transcription History": "Ver historial de transcripciones",
            "Version": "Versión",
            "History": "Historial",
            "Clear All": "Borrar todo",
            "Search transcriptions…": "Buscar transcripciones…",
            "No transcriptions yet": "No hay transcripciones aún",
            "No results found": "Sin resultados",
            "Record something with ⌥S to get started": "Graba algo con ⌥S para empezar",
            "Copy Text": "Copiar texto",
            "Copied": "¡Copiado!",
            "Delete": "Eliminar",
            "Recording…": "Grabando…",
            "Loading model…": "Cargando modelo…",
            "Done ✓": "Hecho ✓",
        
            "Overlay Size": "Tamaño del overlay",
            "Live Floating Preview": "Vista previa flotante",
            "Statistics": "Estadísticas",
            "Today": "Hoy",
            "This Week": "Esta semana",
            "All Time": "Todo el tiempo",
            "Words Spoken": "Palabras",
            "Characters": "Caracteres",
            "Time Dictated": "Tiempo",
            "Sessions": "Sesiones",
            "Launch at Login": "Abrir al inicio",
            "Sound Feedback": "Retroalimentación",
            "Microphone": "Micrófono",
            "Accessibility": "Accesibilidad",
            "Grant Access": "Dar acceso",
            "Support Scribe": "Apoyar a Scribe",
        
            "Auto Translate to Selected Language": "Traducir automáticamente al idioma seleccionado",
            "Small (Recommended)": "Small (Recomendado)",
            "Great balance of high accuracy and speed (~460MB)": "Gran equilibrio entre alta precisión y velocidad (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "La más alta calidad para discursos y términos complejos (~950MB)",
            "Base (Fastest)": "Base (El más rápido)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Ligero y ultra rápido, ideal para frases simples (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe es un proyecto independiente apoyado en su totalidad por donaciones de usuarios. Si te resulta útil, considera apoyar su desarrollo. Las donaciones son completamente opcionales. ¡Gracias!",
            "Buy Me a Coffee on Ko-fi": "Cómprame un café en Ko-fi",
            "or Crypto": "o Cripto"
        ],
        "de": [
            "Start Dictation": "Diktat starten",
            "Stop Dictation": "Diktat beenden",
            "Transcribing…": "Transkribieren…",
            "Hotkey: ⌥S": "Tastenkürzel: ⌥S",
            "Settings…": "Einstellungen…",
            "Dictation Language": "Diktatsprache",
            "Interface Language": "Oberflächensprache",
            "Quit Scribe": "Scribe beenden",
            "Scribe Settings": "Scribe-Einstellungen",
            "Recording": "Aufnahme",
            "Global Hotkey": "Globales Tastenkürzel",
            "Paste Mode": "Einfügemodus",
            "Replace": "Ersetzen",
            "Append": "Anhängen",
            "Replaces clipboard content with transcribed text.": "Ersetzt den Zwischenablage-Inhalt durch transkribierten Text.",
            "Appends transcribed text to current clipboard content.": "Hängt transkribierten Text an aktuellen Zwischenablage-Inhalt an.",
            "Live Preview": "Live-Vorschau",
            "Shows intermediate text while recording": "Zeigt den Text während der Aufnahme an",
            "Preview Background": "Vorschau-Hintergrund",
            "Appearance": "Erscheinungsbild",
            "Theme": "Design",
            "Overlay Style": "Overlay-Stil",
            "Waveform": "Wellenform",
            "Classic": "Klassisch",
            "Panel Appearance": "Panel-Design",
            "Dark": "Dunkel",
            "Light": "Hell",
            "Glass": "Glas",
            "Recognition": "Erkennung",
            "Model Quality": "Modellqualität",
            "Permissions": "Berechtigungen",
            "Accessibility Permission": "Barrierefreiheit-Berechtigung",
            "Granted": "Erteilt",
            "Not Granted": "Nicht erteilt",
            "Microphone Permission": "Mikrofon-Berechtigung",
            "System": "System",
            "View Transcription History": "Transkriptionsverlauf anzeigen",
            "Version": "Version",
            "History": "Verlauf",
            "Clear All": "Alles löschen",
            "Search transcriptions…": "Transkriptionen suchen…",
            "No transcriptions yet": "Noch keine Transkriptionen",
            "No results found": "Keine Ergebnisse gefunden",
            "Record something with ⌥S to get started": "Nehmen Sie etwas mit ⌥S auf, um zu beginnen",
            "Copy Text": "Text kopieren",
            "Copied": "Kopiert!",
            "Delete": "Löschen",
            "Recording…": "Aufnahme…",
            "Loading model…": "Modell laden…",
            "Done ✓": "Fertig ✓",
        
            "Overlay Size": "Overlay-Größe",
            "Live Floating Preview": "Live-Vorschau",
            "Statistics": "Statistiken",
            "Today": "Heute",
            "This Week": "Diese Woche",
            "All Time": "Gesamte Zeit",
            "Words Spoken": "Wörter",
            "Characters": "Zeichen",
            "Time Dictated": "Zeit",
            "Sessions": "Sitzungen",
            "Launch at Login": "Beim Anmelden starten",
            "Sound Feedback": "Sound-Feedback",
            "Microphone": "Mikrofon",
            "Accessibility": "Bedienungshilfen",
            "Grant Access": "Zugriff gewähren",
            "Support Scribe": "Scribe unterstützen",
        
            "Auto Translate to Selected Language": "Automatisch in ausgewählte Sprache übersetzen",
            "Small (Recommended)": "Small (Empfohlen)",
            "Great balance of high accuracy and speed (~460MB)": "Tolles Gleichgewicht zwischen hoher Genauigkeit und Geschwindigkeit (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Höchste Qualität für komplexe Sprache & Begriffe (~950MB)",
            "Base (Fastest)": "Base (Am schnellsten)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Leicht und ultraschnell, ideal für einfache Sätze (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe ist ein unabhängiges Projekt, das ausschließlich durch Benutzerspenden unterstützt wird. Wenn Sie es nützlich finden, ziehen Sie in Betracht, seine Entwicklung zu unterstützen. Spenden sind völlig freiwillig. Vielen Dank!",
            "Buy Me a Coffee on Ko-fi": "Kauf mir einen Kaffee auf Ko-fi",
            "or Crypto": "oder Krypto"
        ],
        "fr": [
            "Start Dictation": "Démarrer la dictée",
            "Stop Dictation": "Arrêter la dictée",
            "Transcribing…": "Transcription…",
            "Hotkey: ⌥S": "Raccourci: ⌥S",
            "Settings…": "Réglages…",
            "Dictation Language": "Langue de dictée",
            "Interface Language": "Langue de l'interface",
            "Quit Scribe": "Quitter Scribe",
            "Scribe Settings": "Réglages de Scribe",
            "Recording": "Enregistrement",
            "Global Hotkey": "Raccourci global",
            "Paste Mode": "Mode de collage",
            "Replace": "Remplacer",
            "Append": "Ajouter",
            "Replaces clipboard content with transcribed text.": "Remplace le presse-papiers par le texte transcrit.",
            "Appends transcribed text to current clipboard content.": "Ajoute le texte transcrit au presse-papiers actuel.",
            "Live Preview": "Aperçu en direct",
            "Shows intermediate text while recording": "Affiche le texte pendant l'enregistrement",
            "Preview Background": "Arrière-plan de l'aperçu",
            "Appearance": "Apparence",
            "Theme": "Thème",
            "Overlay Style": "Style de superposition",
            "Waveform": "Forme d'onde",
            "Classic": "Classique",
            "Panel Appearance": "Apparence du panneau",
            "Dark": "Sombre",
            "Light": "Clair",
            "Glass": "Verre",
            "Recognition": "Reconnaissance",
            "Model Quality": "Qualité du modèle",
            "Permissions": "Autorisations",
            "Accessibility Permission": "Autorisation d'accessibilité",
            "Granted": "Autorisé",
            "Not Granted": "Non autorisé",
            "Microphone Permission": "Autorisation du microphone",
            "System": "Système",
            "View Transcription History": "Afficher l'historique des transcriptions",
            "Version": "Version",
            "History": "Historique",
            "Clear All": "Tout effacer",
            "Search transcriptions…": "Rechercher des transcriptions…",
            "No transcriptions yet": "Pas encore de transcription",
            "No results found": "Aucun résultat trouvé",
            "Record something with ⌥S pour commencer": "Enregistrez avec ⌥S pour commencer",
            "Copy Text": "Copier le texte",
            "Copied": "Copié !",
            "Delete": "Supprimer",
            "Recording…": "Enregistrement…",
            "Loading model…": "Chargement du modèle…",
            "Done ✓": "Terminé ✓",
        
            "Overlay Size": "Taille de la superposition",
            "Live Floating Preview": "Aperçu flottant",
            "Statistics": "Statistiques",
            "Today": "Aujourd'hui",
            "This Week": "Cette semaine",
            "All Time": "Depuis toujours",
            "Words Spoken": "Mots",
            "Characters": "Caractères",
            "Time Dictated": "Temps",
            "Sessions": "Sessions",
            "Launch at Login": "Ouvrir au démarrage",
            "Sound Feedback": "Retour sonore",
            "Microphone": "Microphone",
            "Accessibility": "Accessibilité",
            "Grant Access": "Accorder l'accès",
            "Support Scribe": "Soutenir Scribe",
        
            "Auto Translate to Selected Language": "Traduire automatiquement dans la langue sélectionnée",
            "Small (Recommended)": "Small (Recommandé)",
            "Great balance of high accuracy and speed (~460MB)": "Excellent équilibre entre haute précision et vitesse (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Qualité optimale pour discours et termes complexes (~950MB)",
            "Base (Fastest)": "Base (Le plus rapide)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Léger et ultra rapide, idéal pour phrases simples (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe est un projet indépendant entièrement soutenu par les dons des utilisateurs. Si vous le trouvez utile, pensez à soutenir son développement. Les dons sont totalement optionnels. Merci !",
            "Buy Me a Coffee on Ko-fi": "Offrez-moi un café sur Ko-fi",
            "or Crypto": "ou Crypto"
        ],
        "it": [
            "Start Dictation": "Avvia dettatura",
            "Stop Dictation": "Interrompi dettatura",
            "Transcribing…": "Trascrizione…",
            "Hotkey: ⌥S": "Scorciatoia: ⌥S",
            "Settings…": "Impostazioni…",
            "Dictation Language": "Lingua di dettatura",
            "Interface Language": "Lingua dell'interfaccia",
            "Quit Scribe": "Esci da Scribe",
            "Scribe Settings": "Impostazioni Scribe",
            "Recording": "Registrazione",
            "Global Hotkey": "Scorciatoia globale",
            "Paste Mode": "Modalità incolla",
            "Replace": "Sostituisci",
            "Append": "Aggiungi",
            "Replaces clipboard content with transcribed text.": "Sostituisce gli appunti con il testo trascritto.",
            "Appends transcribed text to current clipboard content.": "Aggiunge il testo trascritto agli appunti attuali.",
            "Live Preview": "Anteprima dal vivo",
            "Shows intermediate text while recording": "Mostra il testo durante la registrazione",
            "Preview Background": "Sfondo anteprima",
            "Appearance": "Aspetto",
            "Theme": "Tema",
            "Overlay Style": "Stile overlay",
            "Waveform": "Forma d'onda",
            "Classic": "Classico",
            "Panel Appearance": "Aspetto pannello",
            "Dark": "Scuro",
            "Light": "Chiaro",
            "Glass": "Vetro",
            "Recognition": "Riconoscimento",
            "Model Quality": "Qualità del modello",
            "Permissions": "Autorizzazioni",
            "Accessibility Permission": "Autorizzazione Accessibilità",
            "Granted": "Consentito",
            "Not Granted": "Non consentito",
            "Microphone Permission": "Autorizzazione Microfono",
            "System": "Sistema",
            "View Transcription History": "Mostra cronologia trascrizioni",
            "Version": "Versione",
            "History": "Cronologia",
            "Clear All": "Cancella tutto",
            "Search transcriptions…": "Cerca trascrizioni…",
            "No transcriptions yet": "Nessuna trascrizione presente",
            "No results found": "Nessun risultato",
            "Record something with ⌥S to get started": "Registra con ⌥S per iniziare",
            "Copy Text": "Copia testo",
            "Copied": "Copiato!",
            "Delete": "Elimina",
            "Recording…": "Registrazione…",
            "Loading model…": "Caricamento modello…",
            "Done ✓": "Fatto ✓",
        
            "Overlay Size": "Dimensione overlay",
            "Live Floating Preview": "Anteprima fluttuante",
            "Statistics": "Statistiche",
            "Today": "Oggi",
            "This Week": "Questa settimana",
            "All Time": "Tutto il tempo",
            "Words Spoken": "Parole",
            "Characters": "Caratteri",
            "Time Dictated": "Tempo",
            "Sessions": "Sessioni",
            "Launch at Login": "Apri al login",
            "Sound Feedback": "Feedback sonoro",
            "Microphone": "Microfono",
            "Accessibility": "Accessibilità",
            "Grant Access": "Concedi l'accesso",
            "Support Scribe": "Supporta Scribe",
        
            "Auto Translate to Selected Language": "Traduci automaticamente nella lingua selezionata",
            "Small (Recommended)": "Small (Consigliato)",
            "Great balance of high accuracy and speed (~460MB)": "Ottimo equilibrio tra elevata precisione e velocità (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Massima qualità per discorsi e termini complessi (~950MB)",
            "Base (Fastest)": "Base (Il più veloce)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Leggero e ultra veloce, ideale per frasi semplici (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe è un progetto indipendente supportato interamente dalle donazioni degli utenti. Se lo trovi utile, prendi in considerazione l'idea di supportarne lo sviluppo. Le donazioni sono completamente opzionali. Grazie!",
            "Buy Me a Coffee on Ko-fi": "Offrimi un caffè su Ko-fi",
            "or Crypto": "o Cripto"
        ],
        "zh": [
            "Start Dictation": "开始听写",
            "Stop Dictation": "停止听写",
            "Transcribing…": "正在转录…",
            "Hotkey: ⌥S": "快捷键: ⌥S",
            "Settings…": "设置…",
            "Dictation Language": "听写语言",
            "Interface Language": "界面语言",
            "Quit Scribe": "退出 Scribe",
            "Scribe Settings": "Scribe 设置",
            "Recording": "录音",
            "Global Hotkey": "全局快捷键",
            "Paste Mode": "粘贴模式",
            "Replace": "替换",
            "Append": "追加",
            "Replaces clipboard content with transcribed text.": "用转录文本替换剪贴板内容。",
            "Appends transcribed text to current clipboard content.": "将转录文本追加到当前剪贴板中。",
            "Live Preview": "实时预览",
            "Shows intermediate text while recording": "在录音时实时显示转录文本",
            "Preview Background": "预览背景",
            "Appearance": "外观",
            "Theme": "主题",
            "Overlay Style": "浮窗样式",
            "Waveform": "波形",
            "Classic": "经典",
            "Panel Appearance": "面板模式",
            "Dark": "深色",
            "Light": "浅色",
            "Glass": "毛玻璃",
            "Recognition": "语音识别",
            "Model Quality": "模型质量",
            "Permissions": "系统权限",
            "Accessibility Permission": "辅助功能权限",
            "Granted": "已授权",
            "Not Granted": "未授权",
            "Microphone Permission": "麦克风权限",
            "System": "系统",
            "View Transcription History": "查看转录历史",
            "Version": "版本",
            "History": "历史记录",
            "Clear All": "清空全部",
            "Search transcriptions…": "搜索历史转录…",
            "No transcriptions yet": "暂无转录记录",
            "No results found": "未找到结果",
            "Record something with ⌥S to get started": "按下 ⌥S 开始录音体验",
            "Copy Text": "复制文本",
            "Copied": "已复制！",
            "Delete": "删除",
            "Recording…": "录音中…",
            "Loading model…": "正在加载模型…",
            "Done ✓": "完成 ✓",
        
            "Overlay Size": "覆盖层大小",
            "Live Floating Preview": "实时悬浮预览",
            "Statistics": "统计",
            "Today": "今天",
            "This Week": "本周",
            "All Time": "所有时间",
            "Words Spoken": "字数",
            "Characters": "字符数",
            "Time Dictated": "听写时间",
            "Sessions": "会话",
            "Launch at Login": "登录时启动",
            "Sound Feedback": "声音反馈",
            "Microphone": "麦克风",
            "Accessibility": "辅助功能",
            "Grant Access": "授权",
            "Support Scribe": "支持 Scribe",
        
            "Auto Translate to Selected Language": "自动翻译为所选语言",
            "Small (Recommended)": "Small (推荐)",
            "Great balance of high accuracy and speed (~460MB)": "高精度和速度的完美平衡 (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "复杂语音和术语的最高质量 (~950MB)",
            "Base (Fastest)": "Base (最快)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "轻量超快，简单短语的理想选择 (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe是一个完全由用户捐助支持的独立项目。如果您觉得它有用，请考虑支持它的开发。捐助完全是自愿的。谢谢您！",
            "Buy Me a Coffee on Ko-fi": "在Ko-fi上请我喝杯咖啡",
            "or Crypto": "或使用加密货币"
        ],
        "ja": [
            "Start Dictation": "音声入力を開始",
            "Stop Dictation": "音声入力を停止",
            "Transcribing…": "文字起こし中…",
            "Hotkey: ⌥S": "ショートカット: ⌥S",
            "Settings…": "設定…",
            "Dictation Language": "入力言語",
            "Interface Language": "表示言語",
            "Quit Scribe": "Scribe を終了",
            "Scribe Settings": "Scribe 設定",
            "Recording": "録音",
            "Global Hotkey": "グローバルショートカット",
            "Paste Mode": "貼り付けモード",
            "Replace": "置換",
            "Append": "追加",
            "Replaces clipboard content with transcribed text.": "クリップボードの内容を認識テキストで置換します。",
            "Appends transcribed text to current clipboard content.": "現在のクリップボード内容に認識テキストを追加します。",
            "Live Preview": "ライブプレビュー",
            "Shows intermediate text while recording": "録音中にリアルタイムでテキストを表示します",
            "Preview Background": "プレビュー背景",
            "Appearance": "外観",
            "Theme": "テーマ",
            "Overlay Style": "オーバーレイスタイル",
            "Waveform": "波形",
            "Classic": "クラシック",
            "Panel Appearance": "パネル外観",
            "Dark": "ダーク",
            "Light": "ライト",
            "Glass": "グラス",
            "Recognition": "音声認識",
            "Model Quality": "モデルの品質",
            "Permissions": "権限",
            "Accessibility Permission": "アクセシビリティ権限",
            "Granted": "許可済み",
            "Not Granted": "未許可",
            "Microphone Permission": "マイク権限",
            "System": "システム",
            "View Transcription History": "文字起こし履歴を表示",
            "Version": "バージョン",
            "History": "履歴",
            "Clear All": "すべて消去",
            "Search transcriptions…": "履歴を検索…",
            "No transcriptions yet": "履歴はまだありません",
            "No results found": "該当する結果がありません",
            "Record something with ⌥S to get started": "⌥S を押して録音を開始してください",
            "Copy Text": "テキストをコピー",
            "Copied": "コピーしました！",
            "Delete": "削除",
            "Recording…": "録音中…",
            "Loading model…": "モデル読み込み中…",
            "Done ✓": "完了 ✓",
        
            "Overlay Size": "オーバーレイサイズ",
            "Live Floating Preview": "ライブフローティングプレビュー",
            "Statistics": "統計",
            "Today": "今日",
            "This Week": "今週",
            "All Time": "全期間",
            "Words Spoken": "話した単語数",
            "Characters": "文字数",
            "Time Dictated": "音声入力時間",
            "Sessions": "セッション",
            "Launch at Login": "ログイン時に起動",
            "Sound Feedback": "サウンドフィードバック",
            "Microphone": "マイク",
            "Accessibility": "アクセシビリティ",
            "Grant Access": "アクセスを許可",
            "Support Scribe": "Scribeを支援",
        
            "Auto Translate to Selected Language": "選択した言語に自動翻訳",
            "Small (Recommended)": "Small (推奨)",
            "Great balance of high accuracy and speed (~460MB)": "高精度と速度の素晴らしいバランス (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "複雑なスピーチや専門用語に最適な最高品質 (~950MB)",
            "Base (Fastest)": "Base (最速)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "軽量で超高速、シンプルなフレーズに最適 (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribeはユーザーからの寄付のみによって支えられている独立したプロジェクトです。もし役に立つと感じたら、開発のサポートをご検討ください。寄付は完全に任意です。ありがとうございます！",
            "Buy Me a Coffee on Ko-fi": "Ko-fiでコーヒーをご馳走する",
            "or Crypto": "または暗号資産"
        ],
        "pt": [
            "Start Dictation": "Iniciar ditado",
            "Stop Dictation": "Parar ditado",
            "Transcribing…": "Transcrevendo…",
            "Hotkey: ⌥S": "Atalho: ⌥S",
            "Settings…": "Configurações…",
            "Dictation Language": "Idioma de ditado",
            "Interface Language": "Idioma da interface",
            "Quit Scribe": "Sair do Scribe",
            "Scribe Settings": "Configurações do Scribe",
            "Recording": "Gravação",
            "Global Hotkey": "Atalho global",
            "Paste Mode": "Modo de colagem",
            "Replace": "Substituir",
            "Append": "Anexar",
            "Replaces clipboard content with transcribed text.": "Substitui a área de transferência pelo texto transcrito.",
            "Appends transcribed text to current clipboard content.": "Adiciona o texto transcrito à área de transferência atual.",
            "Live Preview": "Visualização em tempo real",
            "Shows intermediate text while recording": "Mostra o texto enquanto grava",
            "Preview Background": "Fundo da visualização",
            "Appearance": "Aparência",
            "Theme": "Tema",
            "Overlay Style": "Estilo da sobreposição",
            "Waveform": "Forma de onda",
            "Classic": "Clássico",
            "Panel Appearance": "Aparência do painel",
            "Dark": "Escuro",
            "Light": "Claro",
            "Glass": "Vidro",
            "Recognition": "Reconhecimento",
            "Model Quality": "Qualidade do modelo",
            "Permissions": "Permissões",
            "Accessibility Permission": "Permissão de acessibilidade",
            "Granted": "Concedido",
            "Not Granted": "Não concedido",
            "Microphone Permission": "Permissão do microfone",
            "System": "Sistema",
            "View Transcription History": "Ver histórico de transcrições",
            "Version": "Versão",
            "History": "Histórico",
            "Clear All": "Limpar tudo",
            "Search transcriptions…": "Pesquisar transcrições…",
            "No transcriptions yet": "Nenhuma transcrição ainda",
            "No results found": "Nenhum resultado encontrado",
            "Record something with ⌥S to get started": "Grave algo com ⌥S para começar",
            "Copy Text": "Copiar texto",
            "Copied": "Copiado!",
            "Delete": "Excluir",
            "Recording…": "Gravando…",
            "Loading model…": "Carregando modelo…",
            "Done ✓": "Concluído ✓",
        
            "Overlay Size": "Tamanho do overlay",
            "Live Floating Preview": "Pré-visualização",
            "Statistics": "Estatísticas",
            "Today": "Hoje",
            "This Week": "Esta semana",
            "All Time": "Todo o tempo",
            "Words Spoken": "Palavras",
            "Characters": "Caracteres",
            "Time Dictated": "Tempo",
            "Sessions": "Sessões",
            "Launch at Login": "Iniciar no login",
            "Sound Feedback": "Feedback sonoro",
            "Microphone": "Microfone",
            "Accessibility": "Acessibilidade",
            "Grant Access": "Conceder acesso",
            "Support Scribe": "Apoiar o Scribe",
        
            "Auto Translate to Selected Language": "Traduzir automaticamente para o idioma selecionado",
            "Small (Recommended)": "Small (Recomendado)",
            "Great balance of high accuracy and speed (~460MB)": "Ótimo equilíbrio entre alta precisão e velocidade (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "A mais alta qualidade para fala e termos complexos (~950MB)",
            "Base (Fastest)": "Base (O mais rápido)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Leve e ultra rápido, ideal para frases simples (~140MB)",
            "Scribe is an independent project supported inteiramente por doações de usuários. Se você achar útil, considere apoiar seu desenvolvimento. As doações são completamente opcionais. Obrigado!": "O Scribe é um projeto independente apoiado inteiramente por doações de usuários. Se você achar útil, considere apoiar seu desenvolvimento. As doações são completamente opcionais. Obrigado!",
            "Buy Me a Coffee on Ko-fi": "Compre-me um café no Ko-fi",
            "or Crypto": "ou Cripto"
        ],
        "tr": [
            "Start Dictation": "Dikteyi Başlat",
            "Stop Dictation": "Dikteyi Durdur",
            "Transcribing…": "Dönüştürülüyor…",
            "Hotkey: ⌥S": "Kısayol: ⌥S",
            "Settings…": "Ayarlar…",
            "Dictation Language": "Dikte Dili",
            "Interface Language": "Arayüz Dili",
            "Quit Scribe": "Scribe'dan Çık",
            "Scribe Settings": "Scribe Ayarları",
            "Recording": "Kaydediliyor",
            "Global Hotkey": "Genel Kısayol",
            "Paste Mode": "Yapıştırma Modu",
            "Replace": "Değiştir",
            "Append": "Ekle",
            "Replaces clipboard content with transcribed text.": "Pano içeriğini dönüştürülen metinle değiştirir.",
            "Appends transcribed text to current clipboard content.": "Dönüştürülen metni mevcut panoya ekler.",
            "Live Preview": "Canlı Önizleme",
            "Shows intermediate text while recording": "Kayıt sırasında metni anlık gösterir",
            "Preview Background": "Önizleme Arka Planı",
            "Appearance": "Görünüm",
            "Theme": "Tema",
            "Overlay Style": "Kaplama Stili",
            "Waveform": "Dalga Formu",
            "Classic": "Klasik",
            "Panel Appearance": "Panel Görünümü",
            "Dark": "Koyu",
            "Light": "Açık",
            "Glass": "Cam",
            "Recognition": "Tanıma",
            "Model Quality": "Model Kalitesi",
            "Permissions": "İzinler",
            "Accessibility Permission": "Erişilebilirlik İzni",
            "Granted": "Verildi",
            "Not Granted": "Verilmedi",
            "Microphone Permission": "Mikrofon İzni",
            "System": "Sistem",
            "View Transcription History": "Dönüştürme Geçmişini Görüntüle",
            "Version": "Sürüm",
            "History": "Geçmiş",
            "Clear All": "Tümünü Temizle",
            "Search transcriptions…": "Dönüştürmelerde ara…",
            "No transcriptions yet": "Henüz kaydolmuş metin yok",
            "No results found": "Sonuç bulunamadı",
            "Record something with ⌥S to get started": "Başlamak için ⌥S ile kayıt yapın",
            "Copy Text": "Metni Kopyala",
            "Copied": "Kopyalandı!",
            "Delete": "Sil",
            "Recording…": "Kaydediliyor…",
            "Loading model…": "Model yükleniyor…",
            "Done ✓": "Tamamlandı ✓",
        
            "Overlay Size": "Yer paylaşımı boyutu",
            "Live Floating Preview": "Canlı önizleme",
            "Statistics": "İstatistikler",
            "Today": "Bugün",
            "This Week": "Bu hafta",
            "All Time": "Tüm zamanlar",
            "Words Spoken": "Kelimeler",
            "Characters": "Karakterler",
            "Time Dictated": "Süre",
            "Sessions": "Oturumlar",
            "Launch at Login": "Başlangıçta aç",
            "Sound Feedback": "Sesli geri bildirim",
            "Microphone": "Mikrofon",
            "Accessibility": "Erişilebilirlik",
            "Grant Access": "İzin ver",
            "Support Scribe": "Scribe'ı destekle",
        
            "Auto Translate to Selected Language": "Seçilen dile otomatik çevir",
            "Small (Recommended)": "Small (Önerilen)",
            "Great balance of high accuracy and speed (~460MB)": "Yüksek doğruluk ve hız arasında mükemmel denge (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Karmaşık konuşma ve terimler için en yüksek kalite (~950MB)",
            "Base (Fastest)": "Base (En Hızlı)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Hafif ve ultra hızlı, basit ifadeler için ideal (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe, tamamen kullanıcı bağışlarıyla desteklenen bağımsız bir projedir. Yararlı buluyorsanız gelişimini desteklemeyi düşünebilirsiniz. Bağışlar tamamen isteğe bağlıdır. Teşekkürler!",
            "Buy Me a Coffee on Ko-fi": "Ko-fi'de bana bir kahve ısmarla",
            "or Crypto": "veya Kripto"
        ],
        "uk": [
            "Start Dictation": "Почати диктування",
            "Stop Dictation": "Зупинити диктування",
            "Transcribing…": "Транскрибація…",
            "Hotkey: ⌥S": "Гаряча клавіша: ⌥S",
            "Settings…": "Налаштування…",
            "Dictation Language": "Мова диктування",
            "Interface Language": "Мова інтерфейсу",
            "Quit Scribe": "Завершити Scribe",
            "Scribe Settings": "Налаштування Scribe",
            "Recording": "Запис",
            "Global Hotkey": "Гаряча клавіша",
            "Paste Mode": "Режим вставки",
            "Replace": "Заміна",
            "Append": "Додавання",
            "Replaces clipboard content with transcribed text.": "Замінює вміст буфера обміну розпізнаним текстом.",
            "Appends transcribed text to current clipboard content.": "Додає розпізнаний текст до поточного вмісту буфера.",
            "Live Preview": "Живий перегляд",
            "Shows intermediate text while recording": "Показує текст безпосередньо під час запису",
            "Preview Background": "Фон перегляду",
            "Appearance": "Зовнішній вигляд",
            "Theme": "Тема оформлення",
            "Overlay Style": "Стиль оверлею",
            "Waveform": "Хвиля",
            "Classic": "Класичний",
            "Panel Appearance": "Тема панелі",
            "Dark": "Темна",
            "Light": "Світла",
            "Glass": "Скло",
            "Recognition": "Розпізнавання",
            "Model Quality": "Якість моделі",
            "Permissions": "Дозволи",
            "Accessibility Permission": "Доступ до Універсального доступу",
            "Granted": "Дозволено",
            "Not Granted": "Не дозволено",
            "Microphone Permission": "Доступ до мікрофона",
            "System": "Система",
            "View Transcription History": "Переглянути історію транскрипцій",
            "Version": "Версія",
            "History": "Історія",
            "Clear All": "Очистити все",
            "Search transcriptions…": "Пошук по історії…",
            "No transcriptions yet": "Записів поки немає",
            "No results found": "Нічого не знайдено",
            "Record something with ⌥S to get started": "Натисніть ⌥S щоб почати запис",
            "Copy Text": "Скопіювати текст",
            "Copied": "Скопійовано!",
            "Delete": "Видалити",
            "Recording…": "Запис…",
            "Loading model…": "Завантаження моделі…",
            "Done ✓": "Готово ✓",
        
            "Overlay Size": "Розмір оверлею",
            "Live Floating Preview": "Плаваюче прев'ю",
            "Statistics": "Статистика",
            "Today": "Сьогодні",
            "This Week": "Цього тижня",
            "All Time": "За весь час",
            "Words Spoken": "Слів",
            "Characters": "Символів",
            "Time Dictated": "Час диктування",
            "Sessions": "Сесії",
            "Launch at Login": "Запускати при вході",
            "Sound Feedback": "Звуковий відгук",
            "Microphone": "Мікрофон",
            "Accessibility": "Доступність",
            "Grant Access": "Надати доступ",
            "Support Scribe": "Підтримати Scribe",
        
            "Auto Translate to Selected Language": "Автоматично перекладати обраною мовою",
            "Small (Recommended)": "Small (Рекомендовано)",
            "Great balance of high accuracy and speed (~460MB)": "Чудовий баланс високої точності та швидкості (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Найвища якість для складної мови та термінів (~950MB)",
            "Base (Fastest)": "Base (Найшвидший)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Легкий та надшвидкий, ідеально підходить для простих фраз (~140MB)",
            "Scribe is an independent project supported entirely by user donations. If you find it useful, consider supporting its development. Donations are completely optional. Thank you!": "Scribe — це незалежний проєкт, який повністю підтримується за рахунок пожертв користувачів. Якщо ви вважаєте його корисним, ви можете підтримати його розробку. Пожертви абсолютно добровільні. Дякуємо!"
        ],
        "pl": [
            "Start Dictation": "Rozpocznij dyktowanie",
            "Stop Dictation": "Zatrzymaj dyktowanie",
            "Transcribing…": "Transkrypcja…",
            "Transcribing": "Transkrypcja",
            "Hotkey: ⌥S": "Skrót: ⌥S",
            "Settings…": "Ustawienia…",
            "Dictation Language": "Język dyktowania",
            "Interface Language": "Język interfejsu",
            "Quit Scribe": "Zakończ Scribe",
            "Scribe Settings": "Ustawienia Scribe",
            "General": "Ogólne",
            "Recording": "Nagrywanie",
            "Global Hotkey": "Globalny skrót",
            "Paste Mode": "Tryb wklejania",
            "Replace": "Zastąp",
            "Append": "Dołącz",
            "Live Preview": "Podgląd na żywo",
            "Appearance": "Wygląd",
            "Theme": "Motyw",
            "Overlay Style": "Styl nakładki",
            "Recognition": "Rozpoznawanie",
            "Model Quality": "Jakość modelu",
            "Permissions": "Uprawnienia",
            "History": "Historia",
            "Clear All": "Wyczyść wszystko",
            "Search transcriptions…": "Szukaj transkrypcji…",
            "Copy Text": "Kopiuj tekst",
            "Copied": "Skopiowano!",
            "Delete": "Usuń",
            "Recording…": "Nagrywanie…",
            "Loading model…": "Ładowanie modelu…",
            "Done ✓": "Gotowe ✓",
            "Launch at Login": "Uruchom przy logowaniu",
            "Sound Feedback": "Dźwięk zwrotny",
            "Support Scribe": "Wesprzyj Scribe",
            "Small (Recommended)": "Small (Zalecany)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Base (Fastest)": "Base (Najszybszy)"
        ],
        "nl": [
            "Start Dictation": "Start dicteren",
            "Stop Dictation": "Stop dicteren",
            "Transcribing…": "Transcriberen…",
            "Transcribing": "Transcriberen",
            "Hotkey: ⌥S": "Sneltoets: ⌥S",
            "Settings…": "Instellingen…",
            "Dictation Language": "Dicteertaal",
            "Interface Language": "Interfacetaal",
            "Quit Scribe": "Scribe afsluiten",
            "Scribe Settings": "Scribe Instellingen",
            "General": "Algemeen",
            "Recording": "Opname",
            "Global Hotkey": "Globale sneltoets",
            "Paste Mode": "Plakmodus",
            "Replace": "Vervangen",
            "Append": "Toevoegen",
            "Live Preview": "Live voorbeeld",
            "Appearance": "Weergave",
            "Theme": "Thema",
            "Overlay Style": "Overlay-stijl",
            "Recognition": "Herkenning",
            "Model Quality": "Modelkwaliteit",
            "Permissions": "Machtigingen",
            "History": "Geschiedenis",
            "Clear All": "Alles wissen",
            "Search transcriptions…": "Transcripties zoeken…",
            "Copy Text": "Tekst kopiëren",
            "Copied": "Gekopieerd!",
            "Delete": "Verwijderen",
            "Recording…": "Opnemen…",
            "Loading model…": "Model laden…",
            "Done ✓": "Klaar ✓",
            "Launch at Login": "Starten bij inloggen",
            "Sound Feedback": "Geluidsterugkoppeling",
            "Support Scribe": "Ondersteun Scribe",
            "Small (Recommended)": "Small (Aanbevolen)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Base (Fastest)": "Base (Snelste)"
        ],
        "ko": [
            "Start Dictation": "받아쓰기 시작",
            "Stop Dictation": "받아쓰기 중지",
            "Transcribing…": "텍스트 변환 중…",
            "Transcribing": "텍스트 변환 중",
            "Hotkey: ⌥S": "단축키: ⌥S",
            "Settings…": "설정…",
            "Dictation Language": "받아쓰기 언어",
            "Interface Language": "인터페이스 언어",
            "Quit Scribe": "Scribe 종료",
            "Scribe Settings": "Scribe 설정",
            "General": "일반",
            "Recording": "녹음",
            "Global Hotkey": "글로벌 단축키",
            "Paste Mode": "붙여넣기 모드",
            "Replace": "바꾸기",
            "Append": "추가하기",
            "Live Preview": "실시간 미리보기",
            "Appearance": "화면 설정",
            "Theme": "테마",
            "Overlay Style": "오버레이 스타일",
            "Recognition": "인식",
            "Model Quality": "모델 품질",
            "Permissions": "권한",
            "History": "히스토리",
            "Clear All": "모두 지우기",
            "Search transcriptions…": "변환 검색…",
            "Copy Text": "텍스트 복사",
            "Copied": "복사됨!",
            "Delete": "삭제",
            "Recording…": "녹음 중…",
            "Loading model…": "모델 로딩 중…",
            "Done ✓": "완료 ✓",
            "Launch at Login": "로그인 시 실행",
            "Sound Feedback": "사운드 피드백",
            "Support Scribe": "Scribe 후원",
            "Small (Recommended)": "Small (권장)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Base (Fastest)": "Base (가장 빠름)"
        ],
        "sv": [
            "Start Dictation": "Starta diktering",
            "Stop Dictation": "Stoppa diktering",
            "Transcribing…": "Transkriberar…",
            "Transcribing": "Transkriberar",
            "Hotkey: ⌥S": "Kortkommando: ⌥S",
            "Settings…": "Inställningar…",
            "Dictation Language": "Diktaringsspråk",
            "Interface Language": "Gränssnittsspråk",
            "Quit Scribe": "Avsluta Scribe",
            "Scribe Settings": "Scribe-inställningar",
            "General": "Allmänt",
            "Recording": "Inspelning",
            "Global Hotkey": "Globalt kortkommando",
            "Paste Mode": "Klistra in-läge",
            "Replace": "Ersätt",
            "Append": "Infoga efter",
            "Live Preview": "Förhandsvisning live",
            "Appearance": "Utseende",
            "Theme": "Tema",
            "Overlay Style": "Overlay-stil",
            "Recognition": "Igenkänning",
            "Model Quality": "Modellkvalitet",
            "Permissions": "Behörigheter",
            "History": "Historik",
            "Clear All": "Rensa alla",
            "Search transcriptions…": "Sök transkriptioner…",
            "Copy Text": "Kopiera text",
            "Copied": "Kopierad!",
            "Delete": "Ta bort",
            "Recording…": "Spelar in…",
            "Loading model…": "Laddar modell…",
            "Done ✓": "Klar ✓",
            "Launch at Login": "Starta vid inloggning",
            "Sound Feedback": "Ljudfeedback",
            "Support Scribe": "Stöd Scribe",
            "Small (Recommended)": "Small (Rekommenderas)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Base (Fastest)": "Base (Snabbast)"
        ],
        "kk": [
            "Start Dictation": "Диктантты бастау",
            "Stop Dictation": "Диктантты тоқтату",
            "Transcribing…": "Транскрипциялау…",
            "Transcribing": "Транскрипциялау",
            "Hotkey: ⌥S": "Ыстық перне: ⌥S",
            "Settings…": "Баптаулар…",
            "Dictation Language": "Диктант тілі",
            "Interface Language": "Интерфейс тілі",
            "Quit Scribe": "Scribe жабу",
            "Scribe Settings": "Scribe баптаулары",
            "General": "Негізгі",
            "Recording": "Жазу",
            "Global Hotkey": "Жалпы ыстық перне",
            "Paste Mode": "Қою режимі",
            "Replace": "Алмастыру",
            "Append": "Жалғау",
            "Live Preview": "Алдын ала тікелей көру",
            "Appearance": "Көрініс",
            "Theme": "Тақырып",
            "Overlay Style": "Оверлей стилі",
            "Recognition": "Тану",
            "Model Quality": "Модель сапасы",
            "Permissions": "Рұқсаттар",
            "History": "Тарих",
            "Clear All": "Барлығын тазалау",
            "Search transcriptions…": "Транскрипцияларды іздеу…",
            "Copy Text": "Мәтінді көшіру",
            "Copied": "Көшірілді!",
            "Delete": "Жою",
            "Recording…": "Жазылуда…",
            "Loading model…": "Модель жүктелуде…",
            "Done ✓": "Дайын ✓",
            "Launch at Login": "Жүйеге кіргенде қосу",
            "Sound Feedback": "Дыбыстық кері байланыс",
            "Support Scribe": "Scribe-ты қолдау",
            "Small (Recommended)": "Small (Ұсынылады)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Base (Fastest)": "Base (Ең жылдам)"
        ]
    ]
}

extension String {
    /// Helper to fetch localization for this string key using current UI language code.
    func loc(_ uiLanguage: String) -> String {
        Localization.string(self, lang: uiLanguage)
    }
}
