import Foundation

/// Central localization manager for Scribe interface text.
enum Localization {
    
    /// Returns the localized string for a given key and UI language code.
    static func string(_ key: String, lang: String) -> String {
        let code = effectiveLanguageCode(lang)
        if let langDict = translations[code], let text = langDict[key] {
            return text
        }
        // Fallback to English
        if let enDict = translations["en"], let text = enDict[key] {
            return text
        }
        return key
    }
    
    private static func effectiveLanguageCode(_ lang: String) -> String {
        if lang != "auto" { return lang }
        // Detect system language
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? "en"
        if preferred.hasPrefix("ru") { return "ru" }
        if preferred.hasPrefix("es") { return "es" }
        if preferred.hasPrefix("de") { return "de" }
        if preferred.hasPrefix("fr") { return "fr" }
        if preferred.hasPrefix("it") { return "it" }
        if preferred.hasPrefix("zh") { return "zh" }
        if preferred.hasPrefix("ja") { return "ja" }
        if preferred.hasPrefix("pt") { return "pt" }
        if preferred.hasPrefix("tr") { return "tr" }
        if preferred.hasPrefix("uk") { return "uk" }
        return "en"
    }
    
    // MARK: - Translations Dictionary
    
    private static let translations: [String: [String: String]] = [
        "en": [
            "Start Dictation": "Start Dictation",
            "Stop Dictation": "Stop Dictation",
            "Transcribing…": "Transcribing…",
            "Hotkey: ⌥S": "Hotkey: ⌥S",
            "Settings…": "Settings…",
            "Dictation Language": "Dictation Language",
            "Interface Language": "Interface Language",
            "Quit Scribe": "Quit Scribe",
            "Scribe Settings": "Scribe Settings",
            "Recording": "Recording",
            "Global Hotkey": "Global Hotkey",
            "Paste Mode": "Paste Mode",
            "Replace": "Replace",
            "Append": "Append",
            "Replaces clipboard content with transcribed text.": "Replaces clipboard content with transcribed text.",
            "Appends transcribed text to current clipboard content.": "Appends transcribed text to current clipboard content.",
            "Live Preview": "Live Preview",
            "Shows intermediate text while recording": "Shows intermediate text while recording",
            "Preview Background": "Preview Background",
            "Appearance": "Appearance",
            "Theme": "Theme",
            "Overlay Style": "Overlay Style",
            "Waveform": "Waveform",
            "Classic": "Classic",
            "Panel Appearance": "Panel Appearance",
            "Dark": "Dark",
            "Light": "Light",
            "Glass": "Glass",
            "Recognition": "Recognition",
            "Model Quality": "Model Quality",
            "Permissions": "Permissions",
            "Accessibility Permission": "Accessibility Permission",
            "Granted": "Granted",
            "Not Granted": "Not Granted",
            "Microphone Permission": "Microphone Permission",
            "System": "System",
            "View Transcription History": "View Transcription History",
            "Version": "Version",
            "History": "History",
            "Clear All": "Clear All",
            "Search transcriptions…": "Search transcriptions…",
            "No transcriptions yet": "No transcriptions yet",
            "No results found": "No results found",
            "Record something with ⌥S to get started": "Record something with ⌥S to get started",
            "Copy Text": "Copy Text",
            "Copied": "Copied!",
            "Delete": "Delete",
            "Recording…": "Recording…",
            "Loading model…": "Loading model…",
            "Done ✓": "Done ✓",
            "Small (Recommended)": "Small (Recommended)",
            "Great balance of high accuracy and speed (~460MB)": "Great balance of high accuracy and speed (~460MB)",
            "Large V3 Turbo": "Large V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Highest quality for complex speech & terms (~950MB)",
            "Base (Fastest)": "Base (Fastest)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Lightweight and ultra fast, ideal for simple phrases (~140MB)",
            "Setting a specific language improves accuracy on short phrases.": "Setting a specific language improves accuracy on short phrases.",
            "Lumina": "Lumina",
            "Midnight": "Midnight",
            "Emerald": "Emerald",
            "Auto Translate to Selected Language": "Auto Translate to Selected Language",
            "Minimal": "Minimal",
            "Magic": "Magic",
            "Pulse": "Pulse",
            "Statistics": "Statistics",
            "Today": "Today",
            "This Week": "This Week",
            "All Time": "All Time",
            "Words Spoken": "Words Spoken",
            "Characters": "Characters",
            "Time Dictated": "Time Dictated",
            "Sessions": "Sessions"
        ],
        "ru": [
            "Start Dictation": "Начать диктовку",
            "Stop Dictation": "Остановить диктовку",
            "Transcribing…": "Транскрибация…",
            "Hotkey: ⌥S": "Горячая клавиша: ⌥S",
            "Settings…": "Настройки…",
            "Dictation Language": "Язык диктовки",
            "Interface Language": "Язык интерфейса",
            "Quit Scribe": "Завершить Scribe",
            "Scribe Settings": "Настройки Scribe",
            "Recording": "Запись",
            "Global Hotkey": "Горячая клавиша",
            "Paste Mode": "Режим вставки",
            "Replace": "Замена",
            "Append": "Добавление",
            "Replaces clipboard content with transcribed text.": "Заменяет содержимое буфера обмена на распознанный текст.",
            "Appends transcribed text to current clipboard content.": "Добавляет распознанный текст к текущему содержимому буфера.",
            "Live Preview": "Живой просмотр",
            "Shows intermediate text while recording": "Показывает текст прямо во время записи",
            "Preview Background": "Фон превью",
            "Appearance": "Внешний вид",
            "Theme": "Тема оформления",
            "Overlay Style": "Стиль оверлея",
            "Waveform": "Волна",
            "Classic": "Классический",
            "Panel Appearance": "Тема панели",
            "Dark": "Темная",
            "Light": "Светлая",
            "Glass": "Стекло",
            "Recognition": "Распознавание",
            "Model Quality": "Качество модели",
            "Permissions": "Разрешения",
            "Accessibility Permission": "Доступ к Универсальному доступу",
            "Granted": "Разрешено",
            "Not Granted": "Не разрешено",
            "Microphone Permission": "Доступ к микрофону",
            "System": "Система",
            "View Transcription History": "Открыть историю транскрипций",
            "Version": "Версия",
            "History": "История",
            "Clear All": "Очистить всё",
            "Search transcriptions…": "Поиск по историям…",
            "No transcriptions yet": "Записей пока нет",
            "No results found": "Ничего не найдено",
            "Record something with ⌥S to get started": "Натисніть ⌥S щоб начать запись",
            "Copy Text": "Скопировать текст",
            "Copied": "Скопировано!",
            "Delete": "Удалить",
            "Recording…": "Запись…",
            "Loading model…": "Загрузка модели…",
            "Done ✓": "Готово ✓",
            "Small (Recommended)": "Маленькая (Рекомендуется)",
            "Great balance of high accuracy and speed (~460MB)": "Отличный баланс скорости и точности (~460 МБ)",
            "Large V3 Turbo": "Большая V3 Turbo",
            "Highest quality for complex speech & terms (~950MB)": "Высшее качество для сложной речи и терминов (~950 МБ)",
            "Base (Fastest)": "Базовая (Самая быстрая)",
            "Lightweight and ultra fast, ideal for simple phrases (~140MB)": "Легкая и сверхбыстрая, идеальна для простых фраз (~140 МБ)",
            "Setting a specific language improves accuracy on short phrases.": "Выбор языка вручную улучшает точность на коротких фразах.",
            "Lumina": "Lumina",
            "Midnight": "Midnight",
            "Emerald": "Emerald",
            "Auto Translate to Selected Language": "Автоматический перевод на выбранный язык",
            "Minimal": "Компактный",
            "Magic": "Магия",
            "Pulse": "Пульс",
            "Statistics": "Статистика",
            "Today": "Сегодня",
            "This Week": "На этой неделе",
            "All Time": "За всё время",
            "Words Spoken": "Сказано слов",
            "Characters": "Символов",
            "Time Dictated": "Время диктовки",
            "Sessions": "Сессий"
        ],
        "es": [
            "Start Dictation": "Iniciar dictado",
            "Stop Dictation": "Detener dictado",
            "Transcribing…": "Transcribiendo…",
            "Hotkey: ⌥S": "Atajo: ⌥S",
            "Settings…": "Ajustes…",
            "Dictation Language": "Idioma de dictado",
            "Interface Language": "Idioma de interfaz",
            "Quit Scribe": "Salir de Scribe",
            "Scribe Settings": "Ajustes de Scribe",
            "Recording": "Grabación",
            "Global Hotkey": "Atajo global",
            "Paste Mode": "Modo de pegado",
            "Replace": "Reemplazar",
            "Append": "Añadir",
            "Replaces clipboard content with transcribed text.": "Reemplaza el portapapeles con el texto transcrito.",
            "Appends transcribed text to current clipboard content.": "Añade el texto transcrito al portapapeles actual.",
            "Live Preview": "Vista previa en vivo",
            "Shows intermediate text while recording": "Muestra el texto mientras grabas",
            "Preview Background": "Fondo de vista previa",
            "Appearance": "Apariencia",
            "Theme": "Tema",
            "Overlay Style": "Estilo de superposición",
            "Waveform": "Forma de onda",
            "Classic": "Clásico",
            "Panel Appearance": "Apariencia del panel",
            "Dark": "Oscuro",
            "Light": "Claro",
            "Glass": "Cristal",
            "Recognition": "Reconocimiento",
            "Model Quality": "Calidad del modelo",
            "Permissions": "Permisos",
            "Accessibility Permission": "Permiso de accesibilidad",
            "Granted": "Concedido",
            "Not Granted": "No concedido",
            "Microphone Permission": "Permiso de micrófono",
            "System": "Sistema",
            "View Transcription History": "Ver historial de transcripciones",
            "Version": "Versión",
            "History": "Historial",
            "Clear All": "Borrar todo",
            "Search transcriptions…": "Buscar transcripciones…",
            "No transcriptions yet": "No hay transcripciones aún",
            "No results found": "Sin resultados",
            "Record something with ⌥S to get started": "Graba algo con ⌥S para empezar",
            "Copy Text": "Copiar texto",
            "Copied": "¡Copiado!",
            "Delete": "Eliminar",
            "Recording…": "Grabando…",
            "Loading model…": "Cargando modelo…",
            "Done ✓": "Hecho ✓"
        ],
        "de": [
            "Start Dictation": "Diktat starten",
            "Stop Dictation": "Diktat beenden",
            "Transcribing…": "Transkribieren…",
            "Hotkey: ⌥S": "Tastenkürzel: ⌥S",
            "Settings…": "Einstellungen…",
            "Dictation Language": "Diktatsprache",
            "Interface Language": "Oberflächensprache",
            "Quit Scribe": "Scribe beenden",
            "Scribe Settings": "Scribe-Einstellungen",
            "Recording": "Aufnahme",
            "Global Hotkey": "Globales Tastenkürzel",
            "Paste Mode": "Einfügemodus",
            "Replace": "Ersetzen",
            "Append": "Anhängen",
            "Replaces clipboard content with transcribed text.": "Ersetzt den Zwischenablage-Inhalt durch transkribierten Text.",
            "Appends transcribed text to current clipboard content.": "Hängt transkribierten Text an aktuellen Zwischenablage-Inhalt an.",
            "Live Preview": "Live-Vorschau",
            "Shows intermediate text while recording": "Zeigt den Text während der Aufnahme an",
            "Preview Background": "Vorschau-Hintergrund",
            "Appearance": "Erscheinungsbild",
            "Theme": "Design",
            "Overlay Style": "Overlay-Stil",
            "Waveform": "Wellenform",
            "Classic": "Klassisch",
            "Panel Appearance": "Panel-Design",
            "Dark": "Dunkel",
            "Light": "Hell",
            "Glass": "Glas",
            "Recognition": "Erkennung",
            "Model Quality": "Modellqualität",
            "Permissions": "Berechtigungen",
            "Accessibility Permission": "Barrierefreiheit-Berechtigung",
            "Granted": "Erteilt",
            "Not Granted": "Nicht erteilt",
            "Microphone Permission": "Mikrofon-Berechtigung",
            "System": "System",
            "View Transcription History": "Transkriptionsverlauf anzeigen",
            "Version": "Version",
            "History": "Verlauf",
            "Clear All": "Alles löschen",
            "Search transcriptions…": "Transkriptionen suchen…",
            "No transcriptions yet": "Noch keine Transkriptionen",
            "No results found": "Keine Ergebnisse gefunden",
            "Record something with ⌥S to get started": "Nehmen Sie etwas mit ⌥S auf, um zu beginnen",
            "Copy Text": "Text kopieren",
            "Copied": "Kopiert!",
            "Delete": "Löschen",
            "Recording…": "Aufnahme…",
            "Loading model…": "Modell laden…",
            "Done ✓": "Fertig ✓"
        ],
        "fr": [
            "Start Dictation": "Démarrer la dictée",
            "Stop Dictation": "Arrêter la dictée",
            "Transcribing…": "Transcription…",
            "Hotkey: ⌥S": "Raccourci: ⌥S",
            "Settings…": "Réglages…",
            "Dictation Language": "Langue de dictée",
            "Interface Language": "Langue de l'interface",
            "Quit Scribe": "Quitter Scribe",
            "Scribe Settings": "Réglages de Scribe",
            "Recording": "Enregistrement",
            "Global Hotkey": "Raccourci global",
            "Paste Mode": "Mode de collage",
            "Replace": "Remplacer",
            "Append": "Ajouter",
            "Replaces clipboard content with transcribed text.": "Remplace le presse-papiers par le texte transcrit.",
            "Appends transcribed text to current clipboard content.": "Ajoute le texte transcrit au presse-papiers actuel.",
            "Live Preview": "Aperçu en direct",
            "Shows intermediate text while recording": "Affiche le texte pendant l'enregistrement",
            "Preview Background": "Arrière-plan de l'aperçu",
            "Appearance": "Apparence",
            "Theme": "Thème",
            "Overlay Style": "Style de superposition",
            "Waveform": "Forme d'onde",
            "Classic": "Classique",
            "Panel Appearance": "Apparence du panneau",
            "Dark": "Sombre",
            "Light": "Clair",
            "Glass": "Verre",
            "Recognition": "Reconnaissance",
            "Model Quality": "Qualité du modèle",
            "Permissions": "Autorisations",
            "Accessibility Permission": "Autorisation d'accessibilité",
            "Granted": "Autorisé",
            "Not Granted": "Non autorisé",
            "Microphone Permission": "Autorisation du microphone",
            "System": "Système",
            "View Transcription History": "Afficher l'historique des transcriptions",
            "Version": "Version",
            "History": "Historique",
            "Clear All": "Tout effacer",
            "Search transcriptions…": "Rechercher des transcriptions…",
            "No transcriptions yet": "Pas encore de transcription",
            "No results found": "Aucun résultat trouvé",
            "Record something with ⌥S pour commencer": "Enregistrez avec ⌥S pour commencer",
            "Copy Text": "Copier le texte",
            "Copied": "Copié !",
            "Delete": "Supprimer",
            "Recording…": "Enregistrement…",
            "Loading model…": "Chargement du modèle…",
            "Done ✓": "Terminé ✓"
        ],
        "it": [
            "Start Dictation": "Avvia dettatura",
            "Stop Dictation": "Interrompi dettatura",
            "Transcribing…": "Trascrizione…",
            "Hotkey: ⌥S": "Scorciatoia: ⌥S",
            "Settings…": "Impostazioni…",
            "Dictation Language": "Lingua di dettatura",
            "Interface Language": "Lingua dell'interfaccia",
            "Quit Scribe": "Esci da Scribe",
            "Scribe Settings": "Impostazioni Scribe",
            "Recording": "Registrazione",
            "Global Hotkey": "Scorciatoia globale",
            "Paste Mode": "Modalità incolla",
            "Replace": "Sostituisci",
            "Append": "Aggiungi",
            "Replaces clipboard content with transcribed text.": "Sostituisce gli appunti con il testo trascritto.",
            "Appends transcribed text to current clipboard content.": "Aggiunge il testo trascritto agli appunti attuali.",
            "Live Preview": "Anteprima dal vivo",
            "Shows intermediate text while recording": "Mostra il testo durante la registrazione",
            "Preview Background": "Sfondo anteprima",
            "Appearance": "Aspetto",
            "Theme": "Tema",
            "Overlay Style": "Stile overlay",
            "Waveform": "Forma d'onda",
            "Classic": "Classico",
            "Panel Appearance": "Aspetto pannello",
            "Dark": "Scuro",
            "Light": "Chiaro",
            "Glass": "Vetro",
            "Recognition": "Riconoscimento",
            "Model Quality": "Qualità del modello",
            "Permissions": "Autorizzazioni",
            "Accessibility Permission": "Autorizzazione Accessibilità",
            "Granted": "Consentito",
            "Not Granted": "Non consentito",
            "Microphone Permission": "Autorizzazione Microfono",
            "System": "Sistema",
            "View Transcription History": "Mostra cronologia trascrizioni",
            "Version": "Versione",
            "History": "Cronologia",
            "Clear All": "Cancella tutto",
            "Search transcriptions…": "Cerca trascrizioni…",
            "No transcriptions yet": "Nessuna trascrizione presente",
            "No results found": "Nessun risultato",
            "Record something with ⌥S to get started": "Registra con ⌥S per iniziare",
            "Copy Text": "Copia testo",
            "Copied": "Copiato!",
            "Delete": "Elimina",
            "Recording…": "Registrazione…",
            "Loading model…": "Caricamento modello…",
            "Done ✓": "Fatto ✓"
        ],
        "zh": [
            "Start Dictation": "开始听写",
            "Stop Dictation": "停止听写",
            "Transcribing…": "正在转录…",
            "Hotkey: ⌥S": "快捷键: ⌥S",
            "Settings…": "设置…",
            "Dictation Language": "听写语言",
            "Interface Language": "界面语言",
            "Quit Scribe": "退出 Scribe",
            "Scribe Settings": "Scribe 设置",
            "Recording": "录音",
            "Global Hotkey": "全局快捷键",
            "Paste Mode": "粘贴模式",
            "Replace": "替换",
            "Append": "追加",
            "Replaces clipboard content with transcribed text.": "用转录文本替换剪贴板内容。",
            "Appends transcribed text to current clipboard content.": "将转录文本追加到当前剪贴板中。",
            "Live Preview": "实时预览",
            "Shows intermediate text while recording": "在录音时实时显示转录文本",
            "Preview Background": "预览背景",
            "Appearance": "外观",
            "Theme": "主题",
            "Overlay Style": "浮窗样式",
            "Waveform": "波形",
            "Classic": "经典",
            "Panel Appearance": "面板模式",
            "Dark": "深色",
            "Light": "浅色",
            "Glass": "毛玻璃",
            "Recognition": "语音识别",
            "Model Quality": "模型质量",
            "Permissions": "系统权限",
            "Accessibility Permission": "辅助功能权限",
            "Granted": "已授权",
            "Not Granted": "未授权",
            "Microphone Permission": "麦克风权限",
            "System": "系统",
            "View Transcription History": "查看转录历史",
            "Version": "版本",
            "History": "历史记录",
            "Clear All": "清空全部",
            "Search transcriptions…": "搜索历史转录…",
            "No transcriptions yet": "暂无转录记录",
            "No results found": "未找到结果",
            "Record something with ⌥S to get started": "按下 ⌥S 开始录音体验",
            "Copy Text": "复制文本",
            "Copied": "已复制！",
            "Delete": "删除",
            "Recording…": "录音中…",
            "Loading model…": "正在加载模型…",
            "Done ✓": "完成 ✓"
        ],
        "ja": [
            "Start Dictation": "音声入力を開始",
            "Stop Dictation": "音声入力を停止",
            "Transcribing…": "文字起こし中…",
            "Hotkey: ⌥S": "ショートカット: ⌥S",
            "Settings…": "設定…",
            "Dictation Language": "入力言語",
            "Interface Language": "表示言語",
            "Quit Scribe": "Scribe を終了",
            "Scribe Settings": "Scribe 設定",
            "Recording": "録音",
            "Global Hotkey": "グローバルショートカット",
            "Paste Mode": "貼り付けモード",
            "Replace": "置換",
            "Append": "追加",
            "Replaces clipboard content with transcribed text.": "クリップボードの内容を認識テキストで置換します。",
            "Appends transcribed text to current clipboard content.": "現在のクリップボード内容に認識テキストを追加します。",
            "Live Preview": "ライブプレビュー",
            "Shows intermediate text while recording": "録音中にリアルタイムでテキストを表示します",
            "Preview Background": "プレビュー背景",
            "Appearance": "外観",
            "Theme": "テーマ",
            "Overlay Style": "オーバーレイスタイル",
            "Waveform": "波形",
            "Classic": "クラシック",
            "Panel Appearance": "パネル外観",
            "Dark": "ダーク",
            "Light": "ライト",
            "Glass": "グラス",
            "Recognition": "音声認識",
            "Model Quality": "モデルの品質",
            "Permissions": "権限",
            "Accessibility Permission": "アクセシビリティ権限",
            "Granted": "許可済み",
            "Not Granted": "未許可",
            "Microphone Permission": "マイク権限",
            "System": "システム",
            "View Transcription History": "文字起こし履歴を表示",
            "Version": "バージョン",
            "History": "履歴",
            "Clear All": "すべて消去",
            "Search transcriptions…": "履歴を検索…",
            "No transcriptions yet": "履歴はまだありません",
            "No results found": "該当する結果がありません",
            "Record something with ⌥S to get started": "⌥S を押して録音を開始してください",
            "Copy Text": "テキストをコピー",
            "Copied": "コピーしました！",
            "Delete": "削除",
            "Recording…": "録音中…",
            "Loading model…": "モデル読み込み中…",
            "Done ✓": "完了 ✓"
        ],
        "pt": [
            "Start Dictation": "Iniciar ditado",
            "Stop Dictation": "Parar ditado",
            "Transcribing…": "Transcrevendo…",
            "Hotkey: ⌥S": "Atalho: ⌥S",
            "Settings…": "Configurações…",
            "Dictation Language": "Idioma de ditado",
            "Interface Language": "Idioma da interface",
            "Quit Scribe": "Sair do Scribe",
            "Scribe Settings": "Configurações do Scribe",
            "Recording": "Gravação",
            "Global Hotkey": "Atalho global",
            "Paste Mode": "Modo de colagem",
            "Replace": "Substituir",
            "Append": "Anexar",
            "Replaces clipboard content with transcribed text.": "Substitui a área de transferência pelo texto transcrito.",
            "Appends transcribed text to current clipboard content.": "Adiciona o texto transcrito à área de transferência atual.",
            "Live Preview": "Visualização em tempo real",
            "Shows intermediate text while recording": "Mostra o texto enquanto grava",
            "Preview Background": "Fundo da visualização",
            "Appearance": "Aparência",
            "Theme": "Tema",
            "Overlay Style": "Estilo da sobreposição",
            "Waveform": "Forma de onda",
            "Classic": "Clássico",
            "Panel Appearance": "Aparência do painel",
            "Dark": "Escuro",
            "Light": "Claro",
            "Glass": "Vidro",
            "Recognition": "Reconhecimento",
            "Model Quality": "Qualidade do modelo",
            "Permissions": "Permissões",
            "Accessibility Permission": "Permissão de acessibilidade",
            "Granted": "Concedido",
            "Not Granted": "Não concedido",
            "Microphone Permission": "Permissão do microfone",
            "System": "Sistema",
            "View Transcription History": "Ver histórico de transcrições",
            "Version": "Versão",
            "History": "Histórico",
            "Clear All": "Limpar tudo",
            "Search transcriptions…": "Pesquisar transcrições…",
            "No transcriptions yet": "Nenhuma transcrição ainda",
            "No results found": "Nenhum resultado encontrado",
            "Record something with ⌥S para começar": "Grave algo com ⌥S para começar",
            "Copy Text": "Copiar texto",
            "Copied": "Copiado!",
            "Delete": "Excluir",
            "Recording…": "Gravando…",
            "Loading model…": "Carregando modelo…",
            "Done ✓": "Concluído ✓"
        ],
        "tr": [
            "Start Dictation": "Dikteyi Başlat",
            "Stop Dictation": "Dikteyi Durdur",
            "Transcribing…": "Dönüştürülüyor…",
            "Hotkey: ⌥S": "Kısayol: ⌥S",
            "Settings…": "Ayarlar…",
            "Dictation Language": "Dikte Dili",
            "Interface Language": "Arayüz Dili",
            "Quit Scribe": "Scribe'dan Çık",
            "Scribe Settings": "Scribe Ayarları",
            "Recording": "Kaydediliyor",
            "Global Hotkey": "Genel Kısayol",
            "Paste Mode": "Yapıştırma Modu",
            "Replace": "Değiştir",
            "Append": "Ekle",
            "Replaces clipboard content with transcribed text.": "Pano içeriğini dönüştürülen metinle değiştirir.",
            "Appends transcribed text to current clipboard content.": "Dönüştürülen metni mevcut panoya ekler.",
            "Live Preview": "Canlı Önizleme",
            "Shows intermediate text while recording": "Kayıt sırasında metni anlık gösterir",
            "Preview Background": "Önizleme Arka Planı",
            "Appearance": "Görünüm",
            "Theme": "Tema",
            "Overlay Style": "Kaplama Stili",
            "Waveform": "Dalga Formu",
            "Classic": "Klasik",
            "Panel Appearance": "Panel Görünümü",
            "Dark": "Koyu",
            "Light": "Açık",
            "Glass": "Cam",
            "Recognition": "Tanıma",
            "Model Quality": "Model Kalitesi",
            "Permissions": "İzinler",
            "Accessibility Permission": "Erişilebilirlik İzni",
            "Granted": "Verildi",
            "Not Granted": "Verilmedi",
            "Microphone Permission": "Mikrofon İzni",
            "System": "Sistem",
            "View Transcription History": "Dönüştürme Geçmişini Görüntüle",
            "Version": "Sürüm",
            "History": "Geçmiş",
            "Clear All": "Tümünü Temizle",
            "Search transcriptions…": "Dönüştürmelerde ara…",
            "No transcriptions yet": "Henüz kaydolmuş metin yok",
            "No results found": "Sonuç bulunamadı",
            "Record something with ⌥S to get started": "Başlamak için ⌥S ile kayıt yapın",
            "Copy Text": "Metni Kopyala",
            "Copied": "Kopyalandı!",
            "Delete": "Sil",
            "Recording…": "Kaydediliyor…",
            "Loading model…": "Model yükleniyor…",
            "Done ✓": "Tamamlandı ✓"
        ],
        "uk": [
            "Start Dictation": "Почати диктування",
            "Stop Dictation": "Зупинити диктування",
            "Transcribing…": "Транскрибація…",
            "Hotkey: ⌥S": "Гаряча клавіша: ⌥S",
            "Settings…": "Налаштування…",
            "Dictation Language": "Мова диктування",
            "Interface Language": "Мова інтерфейсу",
            "Quit Scribe": "Завершити Scribe",
            "Scribe Settings": "Налаштування Scribe",
            "Recording": "Запис",
            "Global Hotkey": "Гаряча клавіша",
            "Paste Mode": "Режим вставки",
            "Replace": "Заміна",
            "Append": "Додавання",
            "Replaces clipboard content with transcribed text.": "Замінює вміст буфера обміну розпізнаним текстом.",
            "Appends transcribed text to current clipboard content.": "Додає розпізнаний текст до поточного вмісту буфера.",
            "Live Preview": "Живий перегляд",
            "Shows intermediate text while recording": "Показує текст безпосередньо під час запису",
            "Preview Background": "Фон перегляду",
            "Appearance": "Зовнішній вигляд",
            "Theme": "Тема оформлення",
            "Overlay Style": "Стиль оверлею",
            "Waveform": "Хвиля",
            "Classic": "Класичний",
            "Panel Appearance": "Тема панелі",
            "Dark": "Темна",
            "Light": "Світла",
            "Glass": "Скло",
            "Recognition": "Розпізнавання",
            "Model Quality": "Якість моделі",
            "Permissions": "Дозволи",
            "Accessibility Permission": "Доступ до Універсального доступу",
            "Granted": "Дозволено",
            "Not Granted": "Не дозволено",
            "Microphone Permission": "Доступ до мікрофона",
            "System": "Система",
            "View Transcription History": "Переглянути історію транскрипцій",
            "Version": "Версія",
            "History": "Історія",
            "Clear All": "Очистити все",
            "Search transcriptions…": "Пошук по історії…",
            "No transcriptions yet": "Записів поки немає",
            "No results found": "Нічого не знайдено",
            "Record something with ⌥S to get started": "Натисніть ⌥S щоб почати запис",
            "Copy Text": "Скопіювати текст",
            "Copied": "Скопійовано!",
            "Delete": "Видалити",
            "Recording…": "Запис…",
            "Loading model…": "Завантаження моделі…",
            "Done ✓": "Готово ✓"
        ]
    ]
}

extension String {
    /// Helper to fetch localization for this string key using current UI language code.
    func loc(_ uiLanguage: String) -> String {
        Localization.string(self, lang: uiLanguage)
    }
}
